- docs/awesome.md
- docs/contributing.md
A list of repositories Semgrep Registry automatically crawls.
> Add awesome list

- docs/awesome.md
Update format to match awesome lists: https://github.com/sindresorhus/awesome/blob/main/awesome.md
> Moar awesome

- custom_theme/semgrep-navbar.html
- docs/extra.css
- docs/getting-started.md
> Make the same as semgrep.dev

- docs/writing-rules/testing-rules.md
- mkdocs.yml
Fixes https://github.com/returntocorp/semgrep-docs/issues/22.
> Add rule testing docs

- docs/getting-started.md
Fixes https://github.com/returntocorp/semgrep-app/issues/1019
> Misspellings and numbers

- docs/running-rules.md
For https://github.com/returntocorp/semgrep/issues/1991
> Add note about required space before nosem

- docs/integrations.md
> add generic CI instructions

- docs/experiments.md
- docs/experiments/generic-pattern-matching.md
- docs/experiments/overview.md
- mkdocs.yml
Closes https://github.com/returntocorp/enterprise/issues/479.
> Add 'generic' language section to experiments page

- docs/extra.css
- docs/status.md
Fixes https://github.com/returntocorp/enterprise/issues/472, https://github.com/returntocorp/enterprise/issues/473, https://github.com/returntocorp/enterprise/issues/475. Building on https://r2c.quip.com/K6QoAw79KnAJ/RFC-Semgrep-Language-Maturity-Model.
This a first pass at objectifying our language support. We're aiming for good, not perfect. Notably out of scope, but good candidates for v2:
* Defining what each feature means. These are somewhat opaque identifiers for now.
* Tallying a language's maturity completion. I.e. checking off all the maturity boxes for each language and programmatically determining its maturity.
I'd like to avoid these improvements for now because I'd say were about 70% of the way to automating this information, which will make things much easier in the future. …
> Update supported languages information

- docs/writing-rules/pattern-syntax.md
Gave the pattern syntax a once-over and noticed a few places that could be improved/updated to the latest information.
> Pattern syntax docs touchup

- docs/index.md
> Fix broken Experiments link on index page TOC

- docs/getting-started.md
> Link to CLI usage doc

- README.md
- docs/awesome.md
- docs/getting-started.md
> Misc copy edits

- docs/ignoring-findings.md
> Replace nosem with nosemgrep

- docs/status.md
> Increase languages table iframe width

- docs/writing-rules/rule-syntax.md
Building on https://github.com/returntocorp/semgrep-docs/pull/116. Let me know if I didn't capture the spirit of the original issue, or if there's anything I'm missing :+1:
> Mschwager metavariable regex

- docs/writing-rules/rule-syntax.md
See https://github.com/returntocorp/semgrep-app/issues/2198
> Remove embedded editor and replace with code boxes

- docs/getting-started.md
- docs/index.md
- docs/writing-rules/overview.md
Part 2 coming soon: Upgrading the `rule-ideas` page
> Add some custom rule use cases and the embeditor on popular pages

- docs/writing-rules/rule-ideas.md
> Fix broken img link; add dimensions and title attributes to all embeditors

- README.md
- custom_theme/base.html
- docs/cli-usage.md
- docs/experiments/generic-pattern-matching.md
- docs/experiments/overview.md
- docs/extensions.md
- docs/faq.md
- docs/getting-started.md
- docs/ignoring-findings.md
- docs/integrations.md
- docs/managing-findings.md
- docs/managing-policy.md
- docs/metrics.md
- docs/running-rules.md
- docs/sample-ci-configs.md
- docs/semgrep-ci.md
- docs/status.md
- docs/writing-rules/pattern-syntax.md
- docs/writing-rules/rule-ideas.md
- docs/writing-rules/rule-syntax.md
- docs/writing-rules/testing-rules.md
> Append link to get help to most docs pages

- docs/semgrep-ci.md
Should wait to merge until https://github.com/returntocorp/semgrep-action/pull/289 goes in!
> Ci multiple configs

- docs/experiments/overview.md
A snippet says a 1000 words :)
> Use embedditor in experiments page

- docs/experiments/generic-pattern-matching.md
Closes https://github.com/returntocorp/semgrep/issues/2047
> Remove reference to spacecat

- docs/index.md
- docs/semgrep-ci.md
I reviewed page loads and navigation paths for index.md and am incorporating those findings here. Most folks click on Getting Started, but previously that was below the fold for many viewers. We also found that History wasn't being interacted with, but Language Support was.
> Incorporate index.md learnings

- docs/experiments/overview.md
- docs/getting-started.md
- docs/writing-rules/overview.md
- docs/writing-rules/pattern-examples.md
> Live Editor + Editor -> Playground

- .circleci/config.yml
this syncs to the version intended to be used since #200
> Fix mkdocs version used for deploying

- docs/faq.md
- docs/getting-started.md
- docs/ignoring-findings.md
- docs/index.md
- docs/managing-findings.md
- docs/notifications.md
- docs/sample-ci-configs.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/sample-ci-configs.md
- docs/troubleshooting/gitlab-sast.md
- docs/troubleshooting/semgrep-app.md
- mkdocs.yml
- Rewrite sample CI configs
- Split semgrep-ci configuration reference
> Rework CI sample snippets

- docs/writing-rules/pattern-syntax.md
- docs/writing-rules/rule-syntax.md
This diff mostly reorganize and fix what was there already.
Next commit will document some new features like /$XXX/.
> Adjusting pattern-syntax.md with recent features

- docs/cheat-sheets/django-xss.mdx
- docs/cheat-sheets/flask-xss.mdx
- docs/cheat-sheets/go-command-injection.mdx
- docs/cheat-sheets/java-jsp-xss.mdx
- docs/cheat-sheets/rails-xss.mdx
> update cheat-sheets markup

- docs/semgrep-ci/overview.md
see issue at [semgrep.dev/docs/semgrep-ci/overview/](https://www.semgrep.dev/docs/semgrep-ci/overview/) under "Environment Variables"
Original:
PR:
> fixed formatting for env variable section

- docs/experiments/overview.md
> Fix snippet for taint example

- docs/cheat-sheets/django-xss.mdx
- docs/cheat-sheets/flask-xss.mdx
- docs/cheat-sheets/go-command-injection.mdx
- docs/cheat-sheets/java-jsp-xss.mdx
- docs/cheat-sheets/rails-xss.mdx
- src/components/LinkToRegistryRule.js
turn rule ids into links to registry
> Add links to rules in the registry

- docs/cheat-sheets/django-xss.mdx
- docs/cheat-sheets/go-command-injection.mdx
- docs/cheat-sheets/rails-xss.mdx
> fix cheat sheets references block

- docs/experiments/overview.md
- docs/faq.md
- docs/writing-rules/rule-syntax.md
In this case: equivalences, taint-mode, and pattern-where-python
> Flag deprecated features and deprecated experiments

- docs/experiments/overview.md
- docs/writing-rules/data-flow.md
- sidebars.js
> Move data-flow content to its own page inside writing-rules section

- docs/cheat-sheets/python-command-injection.mdx
- sidebars.js
python command injection cheat sheet
> add python command injection cheat sheet

- src/css/custom.css
> Ensure navbar stays at the top of the window

- docs/extensions.md
> Release 0.65.0

- .github/workflows/algolia-scrape.yml
- algolia-config.json
> Use algolia/docsearch-scraper v1.15.0

- docs/running-rules.md
> Document how to use multiple configs simultaneously

- docs/semgrep-app/sso.md
- docusaurus.config.js
- sidebars.js
> Added SSO Configuration docs

- docs/contributing/contributing.md
- docs/faq.md
> Fix broken links and a missing space

- docs/extensions.md
> Release 0.66.0

- algolia-config.json
> Specify the docs sitemap so Algolia can more reliably index the docs

- docs/extensions.md
> Update semgrep version to 0.67.0

- .github/workflows/algolia-scrape.yml
to give time for the deploy to prod job to finish
> Wait before scraping site and updating search index

- .circleci/config.yml
> Fix CircleCI build error

- docs/writing-rules/testing-rules.md
> Add snippet about validating rules

- docs/extensions.md
> Release 0.71.0

- docs/semgrep-ci/sample-ci-configs.md
> added option for scheduling in GitHub actions

- docs/cli-usage.md
- docs/extensions.md
> Release 0.72.0

- docs/extensions.md
> Release 0.73.0

- docs/contributing/troubleshooting.md
> Fix link to Development Workflow in docs

- docs/extensions.md
- docs/index.md
- docs/status.md
test plan:
yarn start
see updated columns in top page and supported-language page
> Adding C++ in experimental and Kotlin as Beta

- docs/troubleshooting/semgrep-cli.md
- sidebars.js
> Add page for advice on troubleshooting semgrep-cli problems

- docs/release-notes.md
> Add release notes for version 0.75.0, fix some typos

- src/css/custom.css
> comment out paragraph rule

- docs/semgrep-app/findings.md
> migrate from quip resulted in styles not correctly formatted — now fixed

- docs/index.md
- docs/status.md
> Update Scala to Beta in lang maturity charts

- docs/semgrep-app/integrations.md
> comment out amazon s3 integrations for now

- docs/extensions.md
> Release 0.76.1

- docs/extensions.md
> Release 0.76.2

- docs/release-notes.md
> Add release notes for version 0.76.0 and subversions, fix typo

- docs/release-notes.md
> Fix minor typo in release notes

- docs/release-notes.md
> Fix release notes

- docs/writing-rules/pattern-syntax.mdx
> Update documentation for typed metavariables

- docs/semgrep-app/notifications.md
- docs/semgrep-ci/overview.md
> Remove CTA for GitLab self-managed beta

- docs/extensions.md
> Release 0.77.0

- docs/cheat-sheets/python-command-injection.mdx
> Typos in python command injection

- docs/release-notes.md
> Include release notes for version 0.77.0

- docs/faq.md
> update faq with latest wording

- docs/index.md
- docs/status.md
> added solidity in experimental

- src/css/custom.css
> added font weight def for dt

- docs/index.md
> Semgrep now supports 20+ languages

- docs/release-notes.md
> .semgrepignore replacing semgrepignore.

- docs/extensions.md
> Release 0.78.0

- docs/experiments/project-depends-on.md
- sidebars.js
> add project-depends-on docs

- docs/extensions.md
> Release 0.79.0

- docs/release-notes.md
> Add release notes for Semgrep v0.78.0

- docs/release-notes.md
> Add release notes for v0.79.0

- docs/troubleshooting/semgrep.md
> Add instructions for login and policy running

- docs/troubleshooting/semgrep.md
> Clean up login instructions

- docs/cli-usage.md
Documentation for  [corresponding PR](https://github.com/returntocorp/semgrep/pull/4529)
> Added: autocomplete documentation

- docs/faq.md
- docs/index.md
- docs/semgrep-app/pricing-and-billing.mdx
> rewrite Playground terms to prevent future collision with Semgrep Editor

- docs/release-notes.md
> Add release notes for v0.80.0 and v0.81.0

- docs/index.md
- docs/status.md
> Add Dockerfile as an experimental language

- docs/faq.md
- docs/licensing.md
- docs/semgrep-registry-license.md
- sidebars.js
> Add new page about Semgrep and Semgrep Registry licensing

- docs/semgrep-app/pricing-and-billing.mdx
> launch updates

- docs/release-notes.md
> Edit description of Dockerfile support in release notes, edit typo

- docs/release-notes.md
> Add release notes for version 0.82.0

- docusaurus.config.js
- package.json
- yarn.lock
> Upgrade Docusaurus (and plugins) to 2.0.0-beta.15

- docs/release-notes.md
- docs/semgrep-ci/configuration-reference.md
- src/css/custom.css
See the Slack discussion: https://returntocorp.slack.com/archives/C02ET43Q83W/p1644863346108659
> Update Semgrep-CI reference with baseline workaround

- docs/ignoring-files-folders-code.md
> Update ignore ops with namespace + how to include /tests

- docs/cli-usage.md
Up-to-date docs for following pull requests
https://github.com/returntocorp/semgrep/pull/4685
https://github.com/returntocorp/semgrep/pull/4716
> Added h option

- .github/pull_request_template.md
> Update pull request template with review steps

- docs/cli-usage.md
I noticed the CLI usage was out-of-date after a conversation on Slack. I copied the most recent CLI help text here.
> Use most-recent privacy doc URL

- docs/release-notes.md
Original draft: https://docs.google.com/document/d/1JrXROUQRaOmlNFV3Xb6A2S6g-Snl1KVoW19pSPfCjrw/edit#
Changelog: https://github.com/returntocorp/semgrep/releases/tag/v0.83.0
> Add release notes version 0.83.0

- docusaurus.config.js
> Update nav links to match rest of Semgrep site

- docs/cli-usage.md
Linear: https://linear.app/r2c/issue/MKT-316/update-semgrep-help-and-cli-docs-with-f-option
> Update -f info to display how to run multiple rule files

- docs/extensions.md
> Added Scanmycode CE (Community Edition)

- docs/experiments/metavariable-analysis.md
> Add docs for metavariable-analysis experiment

- docs/cheat-sheets/go-xss.mdx
fixed some typos tempalte -> template
- [ x] A subject matter expert (SME) reviews the content
- [ x] A technical writer reviews the content or PR
- [ x] This change has no security implications or else you have pinged the security team
- [ x] Redirects are added if the PR changes page URLs
> dyslexia adjustment

- docs/release-notes.md
> Add release notes for version 0.84.0

- docs/cli-usage.md
- docs/running-rules.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
Slack: https://r2c-community.slack.com/archives/CK86BJ5DW/p1646752265856209?thread_ts=1646750695.175009&cid=CK86BJ5DW
> Add running multiple rules

- docs/faq.md
- docs/managing-findings.md
- docs/semgrep-ci/overview.md
- docs/writing-rules/private-rules.md
- docs/writing-rules/rule-ideas.md
> Fix some outdated links

- docs/experiments/join-mode/recursive-joins.md
I just noticed a great PR with the recursive join mode merged, checked, and had some stylistic nits, please check it out.
> Review recursive join 

- docs/release-notes.md
> Add release notes version 0.86.5

- docs/writing-rules/data-flow/taint-mode.md
Follows returntocorp/semgrep#4901
**NOTE:** This should be merged _after_ release 0.87.0 is out.
> Update taint-mode docs

- docs/cli-usage.md
> Sync CLI help with 0.87.0

- docs/experiments/project-depends-on.md
- docs/semgrep-ci/configuration-reference.md
> Fix few typos from recent PRs

- docs/index.md
> Update Scala to GA

- docs/release-notes.md
- docs/writing-rules/data-flow/taint-mode.md
> Add release notes for version 0.87.0

- README.md
> Rephrase README to make local build more obvious.

- docs/getting-started.md
- docs/writing-rules/private-rules.md
This update honors a 0.87 deprecation.
Closes PA-1170
> Update Docker invocations to not rely on entrypoint

- docs/faq.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/sample-ci-configs.md
- docs/troubleshooting/semgrep.md
> More semgrep-agent -> semgrep ci updates

- docs/faq.md
- docs/semgrep-app/notifications.md
- docs/troubleshooting/semgrep.md
> Fix formatting in CI documents and FAQ

- docs/getting-started.md
Closes https://github.com/returntocorp/semgrep/issues/3976
> getting-started: Add docker command to sample projects

- docs/semgrep-ci/sample-ci-configs.md
> More improvements to sample GHA config

- docs/ignoring-files-folders-code.md
> Update nosemgrep docs to better reflect js syntax options

- docs/experiments/join-mode/recursive-joins.md
> Add inline rule example, fix typos

- docs/experiments/join-mode/overview.md
- docs/experiments/join-mode/recursive-joins.md
> Move inline rule example to overview

- .github/workflows/markdown-link-check.yml
Workflow PR, does not affect content.
> temporary fix for mkdown

- docusaurus.config.js
> Add redirect for old providers page

- docs/semgrep-ci/sample-ci-configs.md
Updated the Jenkins snippet in the Sample CI Configurations section to no longer use Docker and switch it to using semgrep ci.
> updated jenkins CI sample snippet

- src/css/custom.css
> Fix colors/contrast of menus and links in tablet-width and narrower views

- docs/semgrep-ci/sample-ci-configs.md
Added a Bitbucket CI snippet to the docs.
> added bitbucket ci config. alligned feature indenting

- docs/faq.md
- docusaurus.config.js
> Add Java syntax highlighting

- docs/writing-rules/pattern-syntax.mdx
Resolves: https://github.com/returntocorp/semgrep-docs/issues/490
> Fix plural of ellipsis to ellipses, fix indefinite article

- docs/writing-rules/rule-syntax.md
test plan:
yarn start
look at http://localhost:3000/docs/writing-rules/rule-syntax/#options
> Add doc about xml_attrs_implicit_ellipsis options

- package.json
- yarn.lock
> bump up to latest version

- docs/deepsemgrep.md
> Fix inline code, fix formatting for better readability of source code

- docs/cli-reference.md
> Bump to 0.94.0

- docs/contributing/contributing-rules.md
> Fix wrong formatting of code snippets

- .github/workflows/markdown-link-check.yml
- algolia-config.json
- docs/faq.md
- docs/supported-languages.md
- docs/writing-rules/data-flow/status.md
- docs/writing-rules/rule-ideas.md
- docusaurus.config.js
- sidebars.js
> De-prioritize release notes in search results

- docs/contributing/contributing-code.md
- docs/contributing/semgrep-contributing.md
- docs/contributing/semgrep-core-contributing.md
- docs/ignoring-files-folders-code.md
- docs/release-notes.md
- docs/writing-rules/rule-syntax.md
- replace-on-build.py
> Update references to semgrep/semgrep directory to semgrep/cli

- docusaurus.config.js
> Add redirect for CLI reference

- docusaurus.config.js
- src/css/custom.css
> Add announcement bar for Semgrep office hours

- docs/supported-languages.md
This will help https://github.com/returntocorp/semgrep/issues/3226
test plan:
nope
> add metavar_ellipsis_args to GA category

- docs/index.md
- docs/troubleshooting/gitlab-sast.md
> Update number of registry rules from 1k to 2k

- docs/index.md
- docs/supported-languages.md
> Add R as experimental and PHP as GA

- docusaurus.config.js
> Remove office hours announcement banner

- docusaurus.config.js
> Add office hours banner for June 29

- docs/semgrep-app/findings.md
- docs/semgrep-app/pricing-and-billing.mdx
> Change unlimited retention to 5 years 

- docs/writing-rules/private-rules.md
Resolves https://linear.app/r2c/issue/MKT-378#comment-32996818
> Update private rules

- algolia-config.json
> increased pagrank for supported-langs

- docusaurus.config.js
> Update office hours

- docs/getting-started.md
- docs/running-rules.md
- docs/writing-rules/overview.md
> Fix typos, edit links to better work with VS code

- docs/getting-started.md
- docs/semgrep-app/getting-started-with-semgrep-app.md
> Correctly format placeholders in code snippets

- docusaurus.config.js
> Change office hours date to July 27th

- docs/cli-reference.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/sample-ci-configs.md
> Remove obsolete notes about config auto process

- docs/support.md
> Add status.semgrep.dev to the docs

- docs/experiments/extract-mode.md
- sidebars.js
Depends on https://github.com/returntocorp/semgrep/pull/5621
> Document extract mode

- docs/experiments/extract-mode.md
> Fix minor stylistic issues in extract mode document

- docs/writing-rules/testing-rules.md
> Fix duplicates, correct typos in testing rules

- docs/index.md
- docs/supported-languages.md
> Add HTML as experimentally supported language

- docs/index.md
- docs/writing-rules/testing-rules.md
> Fix supported languages, fix typo in testing rules

- docusaurus.config.js
> Update announcement banner

- src/components/modules/reference-modules/_supported-languages-table.mdx
Reference in [Slack](https://returntocorp.slack.com/archives/C02JT6YA5S7/p1657923390031169?thread_ts=1657820165.669559&cid=C02JT6YA5S7).
> Removing Hack from experimentally supported languages

- docs/semgrep-app/user-management.md
- (n/a A subject matter expert (SME) reviews the content
- (n./a) Redirects are added if the PR changes page URLs
> replaced analytics, added Editor

- docs/deepsemgrep.md
- docs/experiments/project-depends-on.md
> Make headers stating "supported languages" more specific

- src/css/custom.css
> Fix SVG rendering in dark mode, tweak SVG sizes

- docs/semgrep-ci/sample-ci-configs.md
- [ x] This change has no security implications or else you have pinged the security team
- [ x] Redirects are added if the PR changes page URLs
> one-liner to fix inconsistent Buildkite config 

- docs/semgrep-app/scm.md
- (n/a) A technical writer reviews the content or PR
> removed outdated steps

- docs/getting-started.md
- docs/running-rules.md
> Add direct links to Semgrep Registry to Running rules

- src/css/custom.css
> jetbrains mono update

- docs/semgrep-ci/sample-ci-configs.md
n/a A technical writer reviews the content or PR
> updated that we do not support PR comments except for gh and gl

- docusaurus.config.js
> Remove meetup banner

- src/css/custom.css
For compatibility prefer ligatures off.
Preview
> disable ligatures

- docs/writing-rules/rule-syntax.md
- src/components/modules/reference-modules/_language-extensions-tags.mdx
> Modularize language extensions table

- src/components/modules/reference-modules/_supported-languages-table.mdx
> Change Terraform to GA, add Elixir as an experimental language

- docs/cli-reference.md
> Update CLI reference for semgrep 0.106.0

- .circleci/config.yml
- docs/writing-rules/data-flow/overview.md
- docusaurus.config.js
> Add redirect and delete stale files to fix taint search bug

- sidebars.js
> spell out CLI and CI

- docs/semgrep-app/scm.md
Removed step 1 because the feature is generally available (no longer behind a feature flag).
> (nano-sized) update instructions for SCM

- docs/cli-reference.md
- src/css/custom.css
> Update Semgrep exit codes

- docs/release-notes.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
- src/components/modules/reference-modules/_block-findings-errors-configs.mdx
> Add fail-open changes, --no-suppress-errors and default --suppress-errors

- src/css/custom.css
> Fix issues coming from navbar height

- docs/troubleshooting/semgrep.md
> Fix minor typos in troubleshooting docs

- docs/writing-rules/rule-syntax.md
> Update metavariable-comparison docs

- docs/semgrep-ci/sample-ci-configs.md
- [x ] This change has no security implications or else you have pinged the security team
- [x ] Redirects are added if the PR changes page URLs
> Add azure to sample ci configs

- docs/contributing/semgrep-contributing.md
> Add instructions for adding a new package to the CLI

- docs/semgrep-ci/running-semgrep-ci-without-semgrep-app.md
> nano size cleanup

- docs/semgrep-app/scm.md
> specify that the scm guide is for self-hosted ghe only

- docs/semgrep-app/integrations.md
> [nano] removed inventory (CAI) mention

- docs/getting-started.md
> [nano][chore] update getting-started with python 3.7 requirement

- src/components/concept/_shouldafound.mdx
- src/components/procedure/_shouldafound.mdx
> Improve shouldafound documentation

- docs/semgrep-app/pricing-and-billing.mdx
> Update contact us link

- docs/semgrep-app/dashboard.md
> add section in dashboard docs for new projects filter

- docs/experiments/taint-propagators.md
- sidebars.js
> experiments: Taint propagators

- docs/semgrep-app/rule-board.md
The confirmation step is no longer needed.
> Update "Removing rules or rulesets" on rule board

- docs/release-notes.md
- docs/rule-updates.mdx
> Release notes august 2022

- docs/experiments/taint-propagators.md
- docs/writing-rules/data-flow/taint-mode.md
> Adam add videos

- docs/semgrep-app/dashboard.md
- src/components/Tags.js
- src/css/custom.css
V1 of "Tags": Adds functionality to render frontmatter tags into the docs body. 
Downscoped features:
* Linking to "tags" endpoint
* Componenting
> Sara/mkt 415 pills tagging UI

- docs/experiments/join-mode/overview.md
Based on conversation, here: https://r2c-community.slack.com/archives/CK86BJ5DW/p1661967762717409
> Update join rule example regexes to be more precise.

- docs/semgrep-app/scm.md
- docs/semgrep-ci/running-semgrep-ci-without-semgrep-app.md
> [chore] updated steps in SCM

- docs/semgrep-app/notifications.md
> Fix not loading image

- docusaurus.config.js
Feedback from: https://r2c-community.slack.com/archives/C0242656NQ2/p1663075630057579
> adding redirect based on user feedback

- docs/experiments/taint-labels.md
- docs/writing-rules/data-flow/taint-mode.md
> Update taint mode introduction, minor edits in taint labels

- docs/writing-rules/pattern-syntax.mdx
> Add ellipsis operator scope

- docs/experiments/multiple-focus-metavariables.md
> Fixed multi-focus-metavariable 'advanced' snippet

- docs/semgrep-app/getting-started-with-semgrep-app.md
> Add documentation for how many semgrep versions are supported by the app

- docs/semgrep-sc/sc-getting-started.md
- docs/semgrep-sc/sc-glossary.md
- docs/semgrep-sc/sc-ignoring-deps.md
- docs/semgrep-sc/sc-triage-remediation.md
- sidebars.js
This is just the left sidebar, I separated the branch from the docs content - disregard any information about the titles/content of the docs here
> Left sidebar for SSC

- docs/index.md
> Update docs root page for Semgrep Supply Chain

- docs/release-notes.md
> Fix typo in release notes

- docs/rule-updates.mdx
> Fix wrongly rendered header

- docs/semgrep-app/findings.md
> quick fix to triage by pr comment docs

- docs/semgrep-app/dashboard.md
> Update Semgrep App Dashboard documentation

- docs/getting-started.md
Suggested at https://news.ycombinator.com/item?id=33239671
> getting-started: Show people how to search a simple pattern

- docs/getting-started.md
- docs/playground.md
- docs/rule-updates.mdx
- docs/running-rules.md
- docs/semgrep-app/dashboard.md
- docs/semgrep-app/editor.md
- docs/semgrep-app/getting-started-with-semgrep-app.md
- docs/semgrep-app/rule-board.md
- docs/semgrep-ci/running-semgrep-ci-without-semgrep-app.md
- docs/troubleshooting/gitlab-sast.md
- docs/writing-rules/private-rules.md
> Update links to registry - link to explore rulesets

- docs/semgrep-ci/sample-ci-configs.md
> corrected placement for semgrep_branch

- docs/semgrep-ci/sample-ci-configs.md
> Add GitHub Actions setup video

- docs/semgrep-ci/overview.md
- docs/semgrep-ci/running-semgrep-ci-with-semgrep-app.md
- docs/semgrep-ci/sample-ci-configs.md
> Move GitHub setup video to getting started with app

- docs/cli-reference.md
- docs/playground.md
- src/components/procedure/_shouldafound.mdx
> Add keybindings HTML tags to keybindings described in our docs

- docs/cheat-sheets/python-command-injection.mdx
> Fix outdated link

- docs/extensions.md
- docs/ignoring-files-folders-code.md
> Fix extensions and ignoring files

- docs/semgrep-ci/configuration-reference.md
n/a A technical writer reviews the content or PR
> removed semgrep job url

- docs/release-notes/april-2022.md
- docs/writing-rules/experiments/extract-mode.md
- docs/writing-rules/experiments/symbolic-propagation.md
> Change broken relative links to absolute links

- docs/semgrep-app/findings.md
- docs/semgrep-app/getting-started-with-semgrep-app.md
- docs/semgrep-app/rule-board.md
- docs/writing-rules/data-flow/data-flow-overview.md
> Remove rule recommendations, edit Running a scan, add enable triage through comments

- docs/running-rules.md
- src/css/custom.css
> Don't truncate headline and description on generated index cards

- src/css/custom.css
> Fix truncating generated index card headings and descriptions

- docs/faq.md
- docs/semgrep-app/sso.md
- sidebars.js
> Use sentence case for FAQ, SSO description, and privacy policy

- docusaurus.config.js
> Add products dropdown and login links to docs top navbar

- docs/release-notes/september-2022.md
- docs/semgrep-app/tags.md
- sidebars.js
> Add managing projects through tags

- docusaurus.config.js
> Change footer link to point to Semgrep releases Twitter

- .mlc_config.json
- docs/contributing/adding-a-language.md
> Fix some broken links

- docs/extensions.md
> Add GuardDog to list of tools using Semgrep as an engine

- docs/contributing/contributing-rules.md
- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
> Fix minor issues in contributing-rules, fix section to article in configuring-blocking-and-errors-in-ci

- docs/extensions.md
- docs/ignoring-files-folders-code.md
- docs/release-notes/july-2022.md
- docs/semgrep-app/findings.md
- docs/semgrep-app/getting-started-with-semgrep-app.md
- docs/semgrep-app/integrations.md
- docs/semgrep-app/notifications.md
- docs/semgrep-app/rule-board.md
- docs/semgrep-app/tags.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/running-semgrep-ci-with-semgrep-app.md
- docs/semgrep-ci/running-semgrep-ci-without-semgrep-app.md
- docs/semgrep-sc/sc-getting-started.md
- docs/semgrep-sc/sc-ignoring-deps.md
- src/components/procedure/_ignore-individual-findings.mdx
- src/components/procedure/_remove-rule.mdx
> Add details about new workflow to add files in .semgrepignore through App

- src/components/procedure/_ignore-individual-findings.mdx
- src/components/procedure/_remove-rule.mdx
> Small fixes to used SVG icons and ignoring individual findings

- docs/release-notes/november-2022.md
- docs/release-notes/rule-updates.mdx
- sidebars.js
> Add November 2022 release notes

- docs/release-notes/november-2022.md
> Update release notes november-2022.md

- docs/release-notes/november-2022.md
> Fix small typos in release notes

- docs/ignoring-files-folders-code.md
The docs weren't clear to me here, but searching across github.com gave me a clue that this is how it works.
> document how to include .gitignore in .semgrepignore

- docs/contributing/adding-a-language.md
- docs/ignoring-files-folders-code.md
- docs/semgrep-app/dashboard.md
- docs/supported-languages.md
- docs/writing-rules/experiments/extract-mode.md
- docs/writing-rules/pattern-syntax.mdx
> Fix typos in JavaScript name occurrences

- docs/deepsemgrep.md
> Update DeepSemgrep installation instructions

- docs/writing-rules/pattern-syntax.mdx
> Minor fixes in pattern-syntax

- docs/deepsemgrep/deepsemgrep-examples.md
- docs/deepsemgrep/deepsemgrep-introduction.md
- docs/writing-rules/data-flow/data-flow-overview.md
- docusaurus.config.js
- sidebars.js
> Divide DeepSemgrep documentation, create introduction and examples, create DeepSemgrep category

- .github/workflows/algolia-scrape.yml
> fixes indent

- docs/contributing/contributing.md
- docs/contributing/semgrep-contributing.md
- docs/contributing/updating-a-grammar.md
- docs/deepsemgrep/deepsemgrep-introduction.md
- docs/playground.md
- docs/search_js.js
- docs/semgrep-app/editor.md
- docs/semgrep-app/scm.md
- docs/support.md
- docs/writing-rules/experiments/extract-mode.md
- docs/writing-rules/private-rules.md
- docusaurus.config.js
- src/components/MoreHelp.js
> Update links to point to new Semgrep Community Slack

- docs/getting-started.md
> Add tabs to getting started with CLI, edit initial header, minor edits

- docs/supported-languages.md
> Change DeepSemgrep language support from alpha to beta

- docs/contributing/adding-a-language.md
- docs/supported-languages.md
> Add feature and product maturity levels info

- docusaurus.config.js
> Make the left sidebar collapsable

- src/css/custom.css
> Make sidebar collapse button more compatible with our theme

- docs/writing-rules/experiments/extract-mode.md
This is part of a pull request modifying several repositories:
- https://github.com/returntocorp/semgrep/pull/6797
- https://github.com/returntocorp/semgrep-langs/pull/24
- https://github.com/returntocorp/semgrep-interfaces/pull/46
- https://github.com/returntocorp/semgrep-docs/pull/843
> Added documentation for the json key new feature

- docs/cli-reference.md
- docs/semgrep-ci/running-semgrep-ci-without-semgrep-app.md
(n/a) Redirects are added if the PR changes page URLs
(n/a) A subject matter expert (SME) reviews the content
> minor cmd opt correction

- docs/semgrep-app/tags.md
> expanded information about tags

- src/components/reference/_supported-languages-table.mdx
Based on changelog: https://github.com/returntocorp/semgrep/releases/tag/v1.8.0
> added clojure lisp scheme to experimental

- src/components/reference/_supported-languages-table.mdx
> Move Rust to beta level support

- static/fs.js
> Rename FS to avoid namespace conflict

- static/sitemaps/sitemap-registry.xml
> Set sitemap namespace for urlset

- docs/contributing/updating-a-grammar.md
- docs/writing-rules/rule-syntax.md
> Substitute iframes with custom note admonitions and links to Playground, add admonition to another file instead of previously used emoji

- docs/release-notes/january-2023.md
> Updates to Jan 2023 release notes

- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
- src/components/code_snippets/_glcicd-semgrep-app-sast-dash.mdx
- src/components/code_snippets/_glcicd-semgrep-app-sast.mdx
- src/components/code_snippets/_glcicd-semgrep-app-ssc.mdx
- src/components/code_snippets/_glcicd-semgrep-app-standalone-dash.mdx
- src/components/code_snippets/_glcicd-semgrep-app-standalone.mdx
> remove mentions to audit_on

- docs/release-notes/all-release-notes.md
- docs/release-notes/introduction.md
- sidebars.js
> Include release notes into collapsible categories for each year

- docs/semgrep-app/getting-started-with-semgrep-app.md
- docs/semgrep-code/overview.md
- docs/semgrep-sc/sc-getting-started.md
> Remove imported modules that were not used, add imports where modules were actually used

- docs/cli-reference.md
- docs/index.md
- docs/writing-rules/data-flow/taint-mode.md
- docs/writing-rules/experiments/join-mode/overview.md
- docs/writing-rules/rule-ideas.md
- docs/writing-rules/rule-syntax.md
also made a PR for the CLI at
https://github.com/returntocorp/semgrep/pull/7184
> fix a couple of typos in help/usage

- docusaurus.config.js
> Update footer links and labels

- docs/deepsemgrep/deepsemgrep-introduction.md
> adds full command for semgrep ci

- docs/release-notes/february-2023.md
- docs/semgrep-app/findings.md
- sidebars.js
> Add release notes february 2023

- docs/cli-reference.md
> Update exit codes (add exit codes 3 and 14)

- docs/deepsemgrep/deepsemgrep-introduction.md
Update based on: https://github.com/returntocorp/semgrep-docs/pull/891#issuecomment-1450860007
> Revert command for semgrep ci 

- src/components/reference/_supported-languages-table.mdx
> update supported languages for playground support

- src/components/procedure/_integrate-slack.mdx
Our slack app is not yet approved (it will be soon) but until then we should let users know they have to be workspace owners to install the app.
> updated slack app to latest instructions

- docs/contributing/contributing.md
> Link to 'contributing code' from 'contributing'

- docs/contributing/contributing-rules.md
- docs/writing-rules/private-rules.md
> Add deleting private rules, add creating private rules from SCP and command line

- docusaurus.config.js
> Update top navigation - from Semgrep App to Semgrep Code

- docs/semgrep-sc/sc-getting-started.md
- docs/semgrep-sc/sc-overview.md
> Substitute two occurrences of Semgrep App with Semgrep Cloud Platform

- docs/release-notes/rule-updates.mdx
> Rule updates Feb 2023

- docs/semgrep-app/sso.md
Just a couple of small fixes. IIRC there is some other work coming for this page, but I figured I'd propose these quick/simple changes now.
> Small typo fixes on SSO page

- docs/faq.md
> Update FAQs with licensing details

- docs/licensing.md
> Add a link from Licensing page to FAQs

- docs/contributing/contributing-rules.md
> Add updating existing rules section

- docs/extensions.md
- docs/ignoring-files-folders-code.md
> Revert to DEFAULT_SEMGREPIGNORE_TEXT and SEMGREP_VERSION_LATEST

- docs/release-notes/february-2023.md
- docs/release-notes/march-2023.md
- docs/writing-rules/data-flow/data-flow-overview.md
> Minor patch for relase notes and links

- docs/release-notes/march-2023.md
> Fix code snippet, fix link

- docs/ignoring-files-folders-code.md
- docs/release-notes/march-2023.md
- docs/semgrep-code/findings.md
- docs/semgrep-code/pro-rules.md
- docs/semgrep-code/rule-board.md
- src/components/procedure/_remove-ruleset.mdx
> Fix disabling rules and removing rulesets (Rule board management), update release notes

- docs/cli-reference.md
> Update CLI reference

- docs/release-notes/march-2023.md
> Update release notes March 2023

- docs/writing-rules/rule-syntax.md
> Add descriptive a link text

- docs/release-notes/january-2023.md
- docs/release-notes/october-2022.md
- docs/semgrep-supply-chain/getting-started.md
- docs/semgrep-supply-chain/glossary.md
- docs/semgrep-supply-chain/overview.md
- docs/semgrep-supply-chain/triage-remediation.md
- docs/supported-languages.md
~~- [ ] A subject matter expert (SME) reviews the content~~ not necessary for PR
> update more links

- docs/cheat-sheets/django-xss.mdx
- docs/cheat-sheets/express-xss.mdx
- docs/cheat-sheets/flask-xss.mdx
- docs/cheat-sheets/go-command-injection.mdx
- docs/cheat-sheets/go-xss.mdx
- docs/cheat-sheets/java-code-injection.mdx
- docs/cheat-sheets/java-command-injection.mdx
- docs/cheat-sheets/java-jsp-xss.mdx
- docs/cheat-sheets/java-xxe.mdx
- docs/cheat-sheets/javascript-code-injection.mdx
- docs/cheat-sheets/javascript-command-injection.mdx
- docs/cheat-sheets/python-code-injection.mdx
- docs/cheat-sheets/python-command-injection.mdx
- docs/cheat-sheets/rails-xss.mdx
- docs/cheat-sheets/ruby-code-injection.mdx
- docs/cheat-sheets/ruby-command-injection.mdx
- src/components/code_snippets/_cheat-sheets-recommended-rule-set.mdx
- Create recommended rule set module (recommend p/default)
- Include the module in cheat sheets
> Substitute outdated rule recommendations in cheat sheets

- docs/cheat-sheets/java-xxe.mdx
> Remove default rules recommendation from XXE cheat sheet (Pro rules are necessary)

- docs/writing-rules/rule-ideas.md
> Minor edits and typo fixes in rule-ideas

- docs/writing-rules/autofix.md
> Add Transforming code with Semgrep autofix video to Autofix documentation

- docs/cheat-sheets/java-xxe.mdx
- docs/writing-rules/experiments/taint-labels.md
> Add video: Catching XXE bugs in Java with Semgrep taint labels

- CODE_OF_CONDUCT.md
- docs/cli-reference.md
- docs/faq.md
- docs/release-notes/march-2023.md
- docs/security.md
- docs/semgrep-cloud-platform/getting-started.md
- docs/semgrep-cloud-platform/pricing-and-billing.mdx
- docs/semgrep-cloud-platform/scm.md
- docs/semgrep-cloud-platform/sso.md
- docs/semgrep-cloud-platform/user-management.md
- docs/semgrep-code/getting-started.md
- docs/semgrep-code/notifications.md
- docs/support.md
- docs/supported-languages.md
- docs/writing-rules/private-rules.md
- docusaurus.config.js
- src/components/reference/_admonition-ssc-license.md
> Update references @r2c → @semgrep

- docs/semgrep-code/semgrep-pro-engine-examples.md
- docs/semgrep-code/semgrep-pro-engine-intro.md
> Substitute embedded code snippets - include interfile: true key under metadata key - improve related descriptions

- docs/supported-languages.md
> Add GA languages from OSS Engine to Pro Engine supported languages

- docs/writing-rules/experiments/join-mode/overview.md
> Mention Semgrep Pro Engine in Join mode docs

- docs/semgrep-code/semgrep-pro-engine-intro.md
clarify that you have to run this command to update to the latest version of the engine
- [] Redirects are added if the PR changes page URLs
> Use install-semgrep-pro to update to the latest pro engine

- docs/contributing/contributing-rules.md
- docs/contributing/semgrep-core-contributing.md
- docs/faq.md
- docs/semgrep-ci/running-semgrep-ci-with-semgrep-cloud-platform.md
- docs/semgrep-cloud-platform/pricing-and-billing.mdx
- docs/semgrep-code/rule-board.md
- docs/troubleshooting/rules.md
- docs/troubleshooting/semgrep.md
- docs/writing-rules/rule-syntax.md
> fix some typos

- docs/semgrep-code/semgrep-pro-engine-intro.md
Preview of the result:
(I should probably add similar section to our Getting started with Semgrep OSS)
> Add updating Semgrep Pro Engine in CLI

- docs/ignoring-files-folders-code.md
> Add admonition to improve differentiation between ignored files and findings

- docs/release-notes/april-2023.md
- docusaurus.config.js
- sidebars.js
> Add April 2023 release notes

- docs/release-notes/april-2023.md
> Fix wrong link in release notes

- docs/cheat-sheets/go-command-injection.mdx
> Fix titles in go-command-injection.mdx

- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_gha-semgrep-app-sast-dash.mdx
- src/components/code_snippets/_gha-semgrep-app-sast.mdx
- src/components/code_snippets/_gha-semgrep-app-ssc.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone-dash.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone.mdx
- src/components/reference/_block-findings-errors-configs.mdx
Minor update that does not require other items in the list.
~~- [ ] A technical writer reviews the content or PR~~
~~- [ ] This change has no security implications or else you have pinged the security team~~
~~- [ ] Redirects are added if the PR changes page URLs~~
~~- [ ] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link~~
In addition to adding workflow dispatch, I also renamed "Semgrep Code" config snippets to "default" as it now runs both products and is equivalent to the default config file that is seen in SCP (with additional comments.)
> add workflow dispatch

- docs/semgrep-code/semgrep-pro-engine-intro.md
> Semgrep Pro Engine - instruction fixes and wording clarity

- docs/troubleshooting/semgrep.md
> Update troubleshooting details with example and wording clarifications

- docs/writing-rules/experiments/symbolic-propagation.md
Adds a known limitation of symbolic propagation with branching, for clarity.
> Add branching limitation for symbolic propagation

- docs/contributing/contributing-code.md
- docs/contributing/semgrep-core-contributing.md
> update source paths in contributing doc

- docs/semgrep-code/semgrep-pro-engine-intro.md
- docs/supported-languages.md
> Add Semgrep Pro Engine CI scan information, reformat SPE supported langs table, add info admonition

- src/components/reference/_supported-languages-table.mdx
> Update Kotlin support to GA in Semgrep OSS Engine supported languages

- src/components/reference/_required-rule-fields.mdx
> Add explanation of rule severity key

- docs/cli-reference.md
- docs/faq.md
- docs/index.md
- docs/semgrep-ci/ci-environment-variables.md
- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/running-semgrep-ci-with-semgrep-cloud-platform.md
- docs/semgrep-ci/running-semgrep-ci-without-semgrep-cloud-platform.md
- docs/semgrep-ci/sample-ci-configs.md
- docs/semgrep-cloud-platform/bitbucket-pr-comments.md
- docs/semgrep-cloud-platform/dashboard.md
- docs/semgrep-cloud-platform/email.md
- docs/semgrep-cloud-platform/getting-started.md
- docs/semgrep-cloud-platform/github-pr-comments.md
- docs/semgrep-cloud-platform/gitlab-mr-comments.md
- docs/semgrep-cloud-platform/notifications.md
- docs/semgrep-cloud-platform/pricing-and-billing.mdx
- docs/semgrep-cloud-platform/slack.md
- docs/semgrep-cloud-platform/tags.md
- docs/semgrep-cloud-platform/user-management.md
- docs/semgrep-code/demo-project.md
- docs/semgrep-code/editor.md
- docs/semgrep-code/findings.md
- docs/semgrep-code/getting-started.md
- docs/semgrep-code/rule-board.md
- docs/supported-languages.md
- docs/troubleshooting/semgrep-app.md
- docs/troubleshooting/semgrep-ci.md
~~- [ ] A subject matter expert (SME) reviews the content~~ not needed for this PR
> remove mentions of community

- docs/semgrep-code/policies.md
> Minor edits in Policies documentation

- docs/semgrep-code/getting-started.md
> autoscan callout

- docs/extensions.md
> Add semgrep-ci example for pre-commit

- docs/extensions/overview.md
> Use sentence case

- docs/writing-rules/experiments/aliengrep.md
- sidebars.js
The main goal of this document is to let adventurous users experiment with these new features and collect their feedback so we can make adjustments.
> Reference material for Aliengrep

- docs/writing-rules/experiments/aliengrep.md
> Oops - fix formatting

- docs/writing-rules/experiments/aliengrep.md
> Minor updates to Aliengrep

- docusaurus.config.js
> Add office hours banner

- docs/semgrep-cloud-platform/scm.md
- docs/semgrep-cloud-platform/user-management.md
> chore: Rename SCM tab to Source Code Managers

- docs/supported-languages.md
> Update language parse rate for language maturity levels in supported languages

- docs/release-notes/may-2023.md
> Update release notes May - June 9 2023

- docs/getting-started.md
> Update getting started, move mention about Homebrew path from VS Code extension Readme to docs

- docs/writing-rules/experiments/project-depends-on.md
> add a severity

- docs/contributing/semgrep-contributing.md
We no longer run into issues with Brew & M1 macs; removed a couple of lines of outdated info.
> removed outdated info

- docs/getting-started.md
> Reintroduce CLI to Getting started with Semgrep OSS Engine

- docs/writing-rules/rule-syntax.md
- src/components/reference/_language-extensions-languages-key-values.mdx
- src/components/reference/_supported-languages-table.mdx
> Remove duplicate language (TSX for Typescript) from supported langauges tables

- docs/kb/semgrep-cloud-platform/missing-pr-commments.md
Troubleshooting why a PR or MR comments are not working is a very common need. This document pulls together common issues to simplify the troubleshooting process. See [Linear issue](https://linear.app/semgrep/issue/CSE-7/why-am-i-not-receiving-prmr-comments) for more.
> [New KB Article] Why am I not receiving PR/MR comments?

- docs/semgrep-cloud-platform/user-management.md
~~- [ ] A technical writer reviews the content or PR~~ xs size pr
Preview:
> add admonition to reflect changes

- src/components/reference/_triage-states.mdx
> Add info about findings triaged across refs

- docs/release-notes/march-2023.md
- docs/semgrep-code/semgrep-pro-engine-examples.md
- docs/semgrep-code/semgrep-pro-engine-intro.md
- docs/supported-languages.md
> Update Pro Engine toggle

- docs/writing-rules/rule-syntax.md
Two new functions were added to metavariable comparison: strptime and today, this pull request is adding documentation for these new functionalities.
> Adding documentation for new functions strptime and today

- docs/extensions/overview.md
> Remove args vals in semgrep precommit config snippet

- docs/ignoring-files-folders-code.md
- docs/pricing-and-billing.mdx
- docs/release-notes/june-2021.md
- docs/semgrep-cloud-platform/scm.md
- docs/semgrep-code/getting-started.md
**Added PRs to our on-prem guide based on Slack discussion. Fixed some links**
> [chore] add new IPs, fix links, 

- docs/writing-rules/autofix.md
> Add automatically removing a code detected by a rule - with autofix

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
> simplify oss and pro tables

- docs/kb/semgrep-ci/azure-using-templates-with-semgrep.md
> add a new azure article

- docs/kb/rules/understand-severities.md
Provide context on how rule severities are assigned.
> [New KB Article] Understand rule severities

- docs/kb/semgrep-ci/why-duplicate-findings.md
Cover findings duplication as it relates to diff-aware scanning.
> [New KB Article] Why are duplicate findings appearing?

- docs/writing-rules/rule-syntax.md
> add section for metavariable-type

- src/css/custom.scss
> Restrict Extensions > VS Code video width

- docs/semgrep-cloud-platform/github-pr-comments.md
> light wording fixes for GH PR Comments page

- docs/integrating.md
- sidebars.js
> guide for integrators

- docs/kb/rules/run-all-available-rules.md
> Light wording / organization updates to Run all available rules

- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
We currently have some troubleshooting content, but not a general guide to the common troubleshooting steps we recommend.
Most likely we will want to reorganize and enhance this information over time, as well as connect it to specialized articles for further troubleshooting, but I wanted to get started with an initial pass for now.
> [New KB Article] Semgrep scan troubleshooting (initial pass)

- docs/writing-rules/experiments/aliengrep.md
Fixes a typo in a section title
> Fix typo in aliengrep section name

- docs/writing-rules/experiments/metavariable-type.md
- docs/writing-rules/rule-syntax.md
- sidebars.js
> Move metavariable-type doc to experimental

- docs/semgrep-cloud-platform/jira.md
* minor style conformity
* added step for chinmay's form when gaining access
* we don't support data center
> minor updates to jira docs

- docs/index.md
- src/components/reference/_supported-languages-table.mdx
> Add experimental langs back to the language table

- src/components/code_snippets/_jenkins-semgrep-app-sast-docker.mdx
> removed dupe line

- docs/kb/semgrep-supply-chain/scanning-projects-with-multiple-lock-files.md
> add new supply-chain article

- src/components/reference/_supported-languages-table.mdx
> update docs to reflect language maturity level changes

- docs/semgrep-cloud-platform/getting-started.md
Also removed the Team tier mention.
> SCA is no longer gated by contacting Sales

- docs/semgrep-supply-chain/license-compliance.md
Adding some details on the current state of handling for multiple licenses (most strict policy) and package exceptions (version-specific).
> Add details on multiple licenses and exception behavior

- docs/semgrep-supply-chain/triage-remediation.md
I couldn't find this outside our release notes, so adding it here. Also happy to add to the glossary if recommended!
> Supply Chain: Add manual review as exposed under reachable

- docs/semgrep-supply-chain/triage-remediation.md
😶‍🌫️
just fixing my own errors here!
> Fix punctuation error I just introduced

- docs/semgrep-supply-chain/triage-remediation.md
- src/components/reference/_admonition-sot-cves.md
Goal: improve findability using terms such as **coverage** rather than advisories, which is our product term
A reword based on how users try to search for this kind of information. See the linear task for more information.
> reword for better findability

- docs/kb/integrations/semgrep-vs-code-windows.md
- docusaurus.config.js
We were looking for this article today and had trouble finding it in SCP. Even though it requires login, it's more of an integration guide than part of SCP.
> Move VS Code + Semgrep on Windows to integrations category

- docs/writing-rules/rule-syntax.md
> Add documentation for min-version/max-version.

- src/components/reference/_supported-languages-table.mdx
> Add apex to supported languages

- docs/licensing.md
> Update license to reflect new trailofbits rules

- docs/faq.md
> Updating FAQ with Snyk comparison posted on community slack channel

- docs/release-notes/august-2023.md
- docs/release-notes/latest.md
- sidebars.js
This PR includes the new endpoint /latest
> Sara/release notes/aug2023

- docs/supported-languages.md
> SSC C# to Beta

- docs/contributing/contributing.md
- docs/extensions/overview.md
- src/components/reference/_cli-help-output.md
> Document intellij, and update lsp related docs

- docs/cli-reference.md
> remove autocomplete

- src/components/reference/_supported-languages-table.mdx
> remove apex twice

- docs/semgrep-supply-chain/notifications.md
> Clarify wording for SSC PR comments and add info about severity level

- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_circleci-semgrep-app-sast.mdx
- src/components/code_snippets/_circleci-semgrep-app-ssc.mdx
> Improved the CircleCI configuration

- docs/semgrep-supply-chain/notifications.md
> Fix accuracy of info and add link to term definition.

- docs/semgrep-ci/ci-environment-variables.md
> chore: update SEMGREP_REPO_NAME functionality documentation

- docs/semgrep-cloud-platform/asana.md
- docs/semgrep-cloud-platform/jira.md
- docs/semgrep-cloud-platform/linear.md
- docs/semgrep-code/policies.md
> feat: document multiple policies

- docs/release-notes/latest.md
> sync latest with sept 2023

- docs/contributing/semgrep-contributing.md
> corrected command

- docs/kb/integrations/defect-dojo-integration.md
- docs/kb/rules/using-pattern-not-inside.md
- docs/kb/semgrep-ci/azure-using-templates-with-semgrep.md
- docs/kb/semgrep-ci/ci-vs-cli.md
- docs/kb/semgrep-ci/collect-gha-logs.md
- docs/kb/semgrep-ci/github-reusable-workflows-semgrep.md
- docs/kb/semgrep-ci/github-upload-findings-in-security-dashboard.md
- docs/kb/semgrep-ci/jenkins-shared-library-with-semgrep.md
- docs/kb/semgrep-cloud-platform/missing-pr-commments.md
- docs/kb/semgrep-code/InvalidHeaderValue.md
- docs/kb/semgrep-code/finding_all_taints.md
- docs/kb/semgrep-code/gitlab-group-variables.md
- docs/kb/semgrep-supply-chain/scanning_multiple_lockfiles.md
We've got a nice blob of KB articles now, I thought it might be worthwhile to try to get them a bit more in compliance with the overall docs style in a quick pass.
I skilled the GitHub required workflows article because it's likely to need other updates soon due to coming GitHub changes.
> Vale linting & other wording cleanup for KBs

- docs/contributing/semgrep-core-contributing.md
> Update semgrep-core install instructions

- docs/kb/rules/understand-severities.md
There was an errand close paren messing up the link
> Fix link in severities KB

- docs/supported-languages.md
> add support levels to language maturity docs

- docs/semgrep-supply-chain/license-compliance.md
> fix(license): eupl 3.0 doesnt exist

- docs/semgrep-cloud-platform/scm.md
> docs: Update IP list

- docs/semgrep-cloud-platform/sso.md
* Remove tier details, no longer necessary
* Warn about connecting GitHub first (hopefully a temporary warning)
> SSO: Remove tier, recommend GitHub first

- docs/extensions/overview.md
- docs/extensions/semgrep-intellij.md
- sidebars.js
> Add IntelliJ support to supported extensions

- docs/semgrep-cloud-platform/sso.md
I broke the second callout by forgetting to close my new one :)
xs change!
> Fix new warning callout box

- docs/faqs/internal.md
> test internal documentation answers

- src/components/MoreHelp.js
The original wording confused me a bit 😅 
I'll be pushing a bunch of small PRs as I read through the docs and familiarize myself with what I have, instead of making notes on what I want to change and then following through later. No rush on any of them getting reviewed.
> Reword MoreHelp snippet

- docs/semgrep-cloud-platform/user-management.md
Clarify some language and processes around connecting Semgrep orgs to SCM orgs.
> Update user management for clarity on connection

- src/components/reference/_supported-languages-table.mdx
> Update Elixir support

- replace-on-build.py
Our DEFAULT_SEMGREPIGNORE_TEXT broke because it referenced the old returntocorp GH org. This PR fixes that.
> update replace script for build task

- docusaurus.config.js
> semgrep secrets add to navbar

- docs/index.md
> Add history link

- docs/index.md
> correct links locally

- docs/index.md
~~- [ ] A technical writer reviews the content or PR~~ xs size PR
> added quick definitions to index

- docs/semgrep-code/pro-rules.md
Removing incomplete sentence! I tried to look at prior commits to see if anything got deleted and couldn't find anything. Perhaps this is a typo? @s-santillan please verify!
> correct pro rules typo

- docs/semgrep-supply-chain/getting-started.md
- To merge into `supply-chain`.
> minor update to make sure maven users scan successfully

- docs/kb/semgrep-cloud-platform/saml-bad-signature.md
Reword of https://github.com/semgrep/semgrep-docs/pull/1219
> SSO Error bad signature validation

- docs/semgrep-cloud-platform/getting-started.md
Changing the info box to a section so that it can be linked to directly.
> convert info box to section to facilitate linking

- docs/kb/rules/pattern-parse-error.md
- docs/kb/rules/run-all-available-rules.md
- docs/kb/rules/using-pattern-not-inside.md
- docs/kb/semgrep-ci/github-required-workflows-semgrep.md
- docs/kb/semgrep-ci/github-reusable-workflows-semgrep.md
- docs/kb/semgrep-code/InvalidHeaderValue.md
- docs/kb/semgrep-code/gitlab-group-variables.md
- docs/kb/semgrep-code/scanning-large-monorepo.md
This PR pulls in content originally a part of https://github.com/semgrep/semgrep-docs/pull/1214 and https://github.com/semgrep/semgrep-docs/pull/1215.
I skipped the `docs/kb/semgrep-cloud-platform/missing-pr-commments.md` since that was worked on in https://github.com/semgrep/semgrep-docs/pull/1293
> add KB articles

- docs/kb/semgrep-ci/scan-monorepo-in-parts.md
> Scanning a monorepo in parts

- docs/support.md
> add additional info to support doc w/ info for free Pro engine and OSS engine users

- docs/semgrep-cloud-platform/getting-started.md
- docs/semgrep-code/overview.md
~~- [ ] A subject matter expert (SME) reviews the content~~ (n/a; nano-sized update)
> add trail of bits links

- docs/kb/rules/rule-file-perf-principles.md
> add doc on performance principles re: rules and files to consider

- docs/kb/integrations/semgrep-vs-code-windows.md
> add admonition that VS Code now runs natively on Windows

- docs/semgrep-code/policies.md
> clarify what block actually does

- docs/running-rules.md
See https://github.com/semgrep/semgrep/releases/tag/v1.58.0 for info
> add warning that rules stored in a hidden directory are NOT ignored

- docs/kb/semgrep-ci/azure-using-templates-with-semgrep.md
> add flag persistCredentials

- docs/supported-languages.md
Better to refer folks to our page that lists how to get support since there are more options there.
I'm an SME on this, so marking that complete. 😄
> Refer support page for flexibility vs email

- src/components/reference/_admonition-sot-cves.md
Per responsible team, we consume reviewed advisories, so make the link & text specific.
> mention/link specifically to reviewed Advisories

- docs/semgrep-supply-chain/license-compliance.md
- docs/support.md
- src/components/procedure/_detect-gh-repos.md
- src/components/procedure/_platform-detect-ghrepos.md
v small fix to ensure consistency and accuracy
> change instances of 'log into' to 'log in to'

- docs/cheat-sheets/java-xxe.mdx
- docs/contributing/adding-a-language.md
- docs/contributing/semgrep-core-contributing.md
- docs/contributing/updating-a-grammar.md
- docs/index.md
- docusaurus.config.js
> finish some renames that were missed in PR #1362

- docs/faq.md
> Add more details to comparison FAQ

- docs/writing-rules/experiments/pattern-syntax.md
- sidebars.js
> add doc on experiment rules syntax

- sidebars.js
> update link to redoc api

- docs/semgrep-code/semgrep-assistant-code.md
[Context](https://github.com/semgrep/semgrep-docs/pull/1348)
> clarify Assistant's privacy policy re: code deletion

- docusaurus.config.js
> missed redirects

- src/css/custom.scss
@khorne3 you can pull this to check if you like the effect.
The following docs use details:
deployment/add-semgrep-other-ci.md
semgrep-ci/sample-ci-configs.md
semgrep-ci/running-semgrep-ci-with-semgrep-cloud-platform.md
getting-started.md
> unset the background color for details

- docs/semgrep-cloud-platform/slack.md
> Update slack.md: clarifying private channel notification prerequisites

- docs/semgrep-supply-chain/getting-started.md
We were missing some updates to the features we have (PR blocking) and also said some things that aren't quite right.
> Various updates to "Customization"

- docs/semgrep-cloud-platform/github-pr-comments.md
-----
The text for a git merge conflict was committed to the repo. I removed it.
> Remove git merge conflict artifacts from the file

- docs/kb/semgrep-cloud-platform/sso-attribute-error.md
Sometimes linking to redirected pages is flaky, so might as well update to the correct links.
> Link directly to avoid flaky redirect behavior

- docs/kb/semgrep-ci/collect-gitlab-logs.md
> add new kb to gather Gitlab logs

- docs/faq.md
- docs/troubleshooting/rules.md
- docs/troubleshooting/semgrep-app.md
- docs/troubleshooting/semgrep-ci.md
…Help
See [Slack](https://semgrepinc.slack.com/archives/C02PV1VVAUR/p1709146303546559?thread_ts=1709144670.715119&cid=C02PV1VVAUR)
> remove phone and extraneous messages that are already covered by MoreHelp

- docs/semgrep-ci/network-broker.md
> Fix hex converter URL

- .github/workflows/build-and-deploy.yml
- .github/workflows/test-build.yml
Force merging this in an act of supreme desperation.
> upgrade to node 20

- docs/writing-rules/experiments/symbolic-propagation.md
[Slack conversation](https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1709329769798469)
I've verified and fixed the example so that there are no matches in `test2`.
> correct example in Limitations of symbolic propagation section

- docusaurus.config.js
Updating the tag to use the new GA4 property.
> update GA tracking tag

- docs/semgrep-supply-chain/overview.md
Fixes a small typo in the Supply Chain overview
> Singular chain, not plural chains

- docs/kb/semgrep-supply-chain/ssc-lockfiles-circleci.md
> add kb about ssc and circleci

- docs/update.md
> Change Docker image name

- docs/semgrep-supply-chain/triage-remediation.md
Fixes some small style issues - mismatched capitalization with the UI, lack of bolding.
> Fix some small style issues on SSC's Triage and Remediation

- docs/deployment/add-semgrep-other-ci.md
- docs/deployment/deployment-checklist.md
- docs/getting-started.md
- docs/kb/semgrep-supply-chain/ssc-lockfiles-circleci.md
- docs/running-rules.md
- docs/update.md
Quick fixes to clean up (mostly Docker) usage instructions
> fix issues with repo/image names; update Docker instructions

- docs/kb/semgrep-cloud-platform/sso-attribute-error.md
This was going to the wrong place because I forgot a leading slash 🤦🏻‍♀️
~- [ ] A subject matter expert (SME) reviews the content~ xs change
> Add a leading slash so SSO link works

- docs/kb/semgrep-ci/bitbuket-jenkins-pipeline-projects.md
- docs/release-notes/february-2024.md
- docs/semgrep-ci/network-broker.md
- sidebars.js
> February 2024 Release Notes

- docs/semgrep-ci/sample-ci-configs.md
Trying to increase visibility on this KB a bit since someone ran into this issue but didn't find it.
> Add link to GL group variables KB on Sample configs

- docs/semgrep-ci/network-broker.md
Correcting:
* Inconsistent variable usage.
* Confusion of terms public key and private key.
* Invalid ipv6 address in the sample config file.
> Correct errors in network-broker.md

- package.json
- yarn.lock
> fix markprompt ui

- docs/semgrep-code/semgrep-pro-engine-intro.md
From a Slack discussion where we're working to clarify how certain interfile behaviors function/can be modified.
* Adds info about interfile fallbacks being defaults
* Link to KB for scan troubleshooting
* Provide more guidance on contacting support
* Small wording improvements
> Add some clarity to fallback behavior, other small adjustments

- src/components/code_snippets/_glcicd-semgrep-app-sast.mdx
This goes along with https://github.com/semgrep/semgrep-app/pull/13206 to better match the two configs and do some minor cleanup. Also related to https://github.com/semgrep/semgrep-docs/pull/1425
> GL sample: Add web source trigger to align with app, cleanup

- docs/semgrep-cloud-platform/bitbucket-pr-comments.md
- src/components/procedure/_receive-comments-scm.mdx
> add ip address snippet to bb pr comments

- docs/deployment/claim-a-license.md
- docs/licensing.md
- docs/usage-and-billing.mdx
- sidebars.js
Minor updates to the Stripe flow.
> update Stripe flow details

- docs/extensions/overview.md
> add note on running Pro rules with pre-commit hook

- docs/kb/semgrep-ci/github-repository-rulesets-semgrep.md
- docs/kb/semgrep-ci/github-upload-findings-in-security-dashboard.md
- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
- docs/semgrep-supply-chain/setup-maven.md
- docs/writing-rules/private-rules.md
- src/components/code_snippets/_gha-semgrep-app-sast-dash.mdx
- src/components/code_snippets/_gha-semgrep-app-sast.mdx
- src/components/code_snippets/_gha-semgrep-app-ssc.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone-dash.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone.mdx
- src/components/code_snippets/_gha-semgrep-oss-sast.mdx
- src/components/reference/_block-findings-errors-configs.mdx
> Sara/mkt 882 document official support for v4 version for GitHub actions

- docs/deployment/deployment-checklist.md
- src/components/concept/_ip_addresses.mdx
> add IP address allowlisting info to deployment checklist

- docs/contributing/contributing-rules.md
- docs/semgrep-code/semgrep-pro-engine-examples.md
> Update references to interfile option that mention metadata field

- docs/semgrep-ci/network-broker.md
> remove gitlab token requirement

- src/components/reference/_supported-languages-table.mdx
Updated supported languages page, based on this product updates: https://semgrep.dev/docs/supported-languages/
> Swift is GA in Semgrep Code

- docs/deployment/connect-scm.md
We probably want to break up this doc at some point.
Links:
- [Request from Slack](https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1711069653625759?thread_ts=1711069574.451819&cid=C02JT6YA5S7).
- [Previous instructions with indentations](https://github.com/semgrep/semgrep-docs/blob/update_help_commands_1.62.0/docs/deployment/connect-scm.md), which I used as a base for the fix.
> corrected some errors in indentation

- docs/index.md
[We don't currently allow free usage of Secrets.](https://semgrepinc.slack.com/archives/CHP7EGY20/p1712183256141239)
> remove incorrect Secrets usage info

- docs/index.md
- docs/release-notes/rule-updates.mdx
- docs/semgrep-supply-chain/overview.md
- docs/writing-rules/autofix.md
> replace r2c with semgrep in url links

- docs/kb/semgrep-cloud-platform/sso-attribute-error.md
We slightly updated the error text generated by the app, and this also adds some small clarifications and link/title fixes.
> Small improvements to attribute error KB

- docs/usage-and-billing.mdx
> add note re: user limits across multiple orgs

- docs/semgrep-code/policies.md
- docs/semgrep-pro-vs-oss.md
- docs/semgrep-secrets/policies.md
- docs/semgrep-secrets/view-triage.md
- src/components/reference/_triage-states.mdx
> add info to distinguish between fixed and removed findings (reliable fixed status)

- src/components/reference/_triage-states.mdx
> feat: document outcome of Reliable Fixed Status in external docs

- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_bitbucket-semgrep-app-sast.mdx
Updated to match functionality of other pipelines. This is also similar to what we have in-app for the bitbucket CI config. We will be updating this as well.
> Update Bitbucket pipeline

- docs/semgrep-ci/ci-environment-variables.md
- docs/semgrep-ci/packages-in-semgrep-docker.md
Somehow there was ~one~ two lonely returntocorp references here
> use semgrep/semgrep consistently

- docs/getting-started/cli.md
- src/components/reference/_export-as.mdx
Adding instructions on combining output flags to get multiple output formats.
> add info on combining output flags

- docusaurus.config.js
> Add redirect for API link

- docs/semgrep-assistant/overview.md
- docs/semgrep-code/findings.md
- docs/semgrep-secrets/rules.md
- docs/semgrep-supply-chain/getting-started.md
I'm sem-grasping at straws here!
Note if you see this first, I fixed the ones in the Teams section in https://github.com/semgrep/semgrep-docs/pull/1516
> Remove more stray SCP instances

- docs/semgrep-appsec-platform/jira.md
@zdhickman proved it to me just now, so making the update!
> It is not in fact possible to create Jira tickets for Always reachables

- docs/semgrep-secrets/conceptual-overview.md
I accidentally deleted the second half of the sentence.
> fix and clean up sentence at the bottom of the Secrets doc

- docs/usage-and-billing.mdx
> update credit card payment information

- docs/semgrep-ci/network-broker.md
This is helpful since the process is slightly different on dedicated tenants.
> Add note about tenancy + broker

- sidebars.js
> move contributing docs from OSS to About Semgrep

- docusaurus.config.js
> Add redirect for /semgrep-secrets/

- docs/kb/semgrep-ci/github-reusable-workflows-semgrep.md
We had a screenshot for this, but not copy-able text. Hopefully this addition will make it a bit easier for people to set up the calling workflow correctly.
> Provide copyable text for calling workflow YAML

- docs/deployment/managed-scanning.md
> rename managed scanning

- algolia-config.json
Testing fix out
[Original request](https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1716333463430489)
> disable typo tolerance for teams and terms

- docs/writing-rules/rule-syntax.md
[Slack](https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1716500295105489)
> fix sample to match description

- docs/supported-languages.md
> update docs with Elixir SSC support info

- docs/supported-languages.md
> add Package.swift file as requirement for the Swift SSC scans

- docs/release-notes/latest.md
- docs/release-notes/may-2024.md
> remove mentions of new triage statuses

- docs/kb/semgrep-appsec-platform/semgrep-login-cli-tenant.md
> add new kb about semgrep login and single-tenant customers

- docs/semgrep-appsec-platform/asana.md
- docs/semgrep-appsec-platform/linear.md
> deprecate docs for asana & linear for now

- docs/semgrep-ci/network-broker.md
> add info on running multiple instances of Semgrep Broker

- docs/semgrep-code/policies.md
how to add rulesets + caveats on mode selected.
> provide information about adding rulesets on set rules

- docs/semgrep-appsec-platform/webhooks.md
Our webhook samples for both scans and findings were out of date.
I believe I've anonymized/fakeified potentially sensitive data, so this change should not have security implications, but feel free to request another review if you disagree!
> Update both webhooks with current keys/format

- docs/kb/semgrep-secrets/per-product-ignore-not-working.md
This PR adds a KB article explaining why secrets ignores might not work for customers.
> Add kb article for secrets ignores

- docs/writing-rules/data-flow/constant-propagation.md
* minor edits to the doc
* added info on constant propagation that would be helpful for troubleshooting
> update content on constant propagation

- docs/deployment/add-semgrep-to-ci.md
- docs/deployment/customize-ci-jobs.md
- docs/semgrep-code/glossary.md
- src/components/procedure/_platform-add-repo.md
- src/components/reference/_default-branches.md
- Explain full scans and diff scans in a more popular doc
- Add list of default branch names in 2 places and modularize so that we can update easily.
You can view this in the deployment preview! 
- https://deploy-preview-1608--semgrep-docs-prod.netlify.app/docs/deployment/add-semgrep-to-ci#default-branch-names
> add list of branch names

- docs/semgrep-appsec-platform/email.md
> clarify notifications and number of emails

- docs/deployment/managed-scanning.md
Flow for context: https://semgrepinc.slack.com/archives/C03A5BETNS3/p1717589886903149
I admit it looks a little dry because the first screenshot is actually to help the user debug. The reason why we have not included screenshots is partially due to the fact that this feature is in **beta**.
> shorten steps now that we have a setup page

- docs/semgrep-appsec-platform/jira.md
We have label support for Jira v3! Adding that to the docs.
> Update Jira docs to clarify label support

- static/fs.js
This PR updates our FullStory tracking snippet with the latest version and our self-hosted relay.
See GROW-247 for more context.
> chore(fullstory): Update FS Snippet

- docs/kb/semgrep-ci/scan-monorepo-in-parts.md
1. # Thanks for improving Semgrep Docs 😀
> Update docs to recommend subdir

- docs/semgrep-ci/network-broker.md
> add Bitbucket usage instructions for network broker

- docs/running-rules.md
No prob.
... skipping these because there are no content changes in this PR.
> Typo fix (let's -> lets)

- docs/contributing/contributing-rules.md
> Replace guardrail with secure default

- docs/release-notes/latest.md
Accidentally overrode metadata with aggressive copy and paste.
> fix metadata for latest.md

- docs/deployment/deployment-checklist.md
Reference: https://github.com/semgrep/semgrep-docs/pull/1634.
> Remove PAT requirement for GHE

- docs/writing-rules/pattern-syntax.mdx
> add pattern syntax new sections

- docs/faq.md
I looked through the history and tried to keep the more recent version, but please double-check me about whether this is the right one to keep.
> Remove duplicate paragraph

- docs/semgrep-ci/sample-ci-configs.md
This is a suggestion from a customer who ran into this problem on several projects. Feel free to rephrase it or decide it would be better elsewhere, but I wanted to pass it along.
> Add size suggestion for bitbucket

- docs/semgrep-ci/network-broker.md
This should help keep folks from getting stuck when setting up the broker with Managed Scans.
> Network Broker: need to allowlist instance base with SMS

- docs/kb/semgrep-ci/using-nonroot-docker-image-with-gha.md
> Using nonroot docker image with GHA

- docs/semgrep-pro-vs-oss.md
This is not actually accurate. Both OSS and Pro support GitLab and SARIF (GitHub) output.
> Remove row from Pro vs OSS table

- docs/semgrep-ci/network-broker.md
Git is tricksy so both GET and POST are needed for this route.
> Add POST for allowlist for use with Managed Scans

- docs/deployment/managed-scanning.md
> remove note about ghes as users can self serve now

- docs/semgrep-appsec-platform/ticketing.md
We're going to remove this page long-term, but short-term let's at least not say it's still private beta, since it isn't.
> Quick fix for Jira private beta info

- docs/semgrep-appsec-platform/slack.md
A small note to single-tenant folks that they need to ensure their tenant is ready for this (recently determined).
> Tenants need a bit of extra love for Slack

- docs/semgrep-appsec-platform/jira.md
> Add Component as a supported Jira field type

- docs/semgrep-ci/network-broker.md
Add note on how to adjust logging on the broker, and warn that it can lead to high memory usage if the req/res are large.
> Network broker: log verbosity howto and gentle warning

- docs/deployment/connect-scm.md
> remove CI instructions from SCM connection page

- docs/semgrep-appsec-platform/bitbucket-cloud-pr-comments.md
Context as to why we explicitly mention **scope**
https://linear.app/semgrep/issue/TEC-108/differentiate-scope-and-permission-in-bb-cloud-and-dc
> update to explicitly mention scope

- docs/semgrep-secrets/historical-scanning.md
redoing https://github.com/semgrep/semgrep-docs/pull/1710
> Update historical scanning doc to contain more info 

- docs/deployment/connect-scm.md
> add mention that Semgrep supports multiple GHE orgs

- docs/deployment/managed-scanning.md
> typo corrections

- docs/semgrep-pro-vs-oss.md
> Fix typos in semgrep-pro-vs-oss.md

- docs/extensions/semgrep-intellij.md
Explain why we can't offer support for IntelliJ Community
> Clarify IntelliJ Community support

- docs/deployment/primary-branch.md
- src/components/concept/_findings-default-view.mdx
Adds the video and beefs up the content on why counts may differ and adds, near the top, a note on what changes users have to be aware of when they opt in.
Here's the link:
https://deploy-preview-1720--semgrep-docs-prod.netlify.app/docs/deployment/primary-branch
Several of Pang's notes on the URL changes are added in as well, **note that for Secrets, since the behavior was still largely legacy, there was no need to include them since there were no changes.**
> update primary branch

- docs/semgrep-appsec-platform/bitbucket-cloud-pr-comments.md
- docs/semgrep-appsec-platform/bitbucket-data-center-pr-comments.md
Adding specific version info for BBDC.
> update docs with versions of BBDC supported

- docs/semgrep-ci/network-broker.md
> add info on enabling verbose WireGuard logging in network broker

- docs/deployment/primary-branch.md
- docs/semgrep-code/findings.md
- docs/semgrep-supply-chain/triage-remediation.md
> Primary branch is now GA

- docs/semgrep-secrets/getting-started.md
> add admonition for getting access to Secrets

- docs/semgrep-code/supported-languages-python.md
- docs/supported-languages.md
- sidebars.js
- src/components/reference/_supported-languages-table.mdx
(wip, need to add the nav bar but would appreciate an early review 🙇 )
> Add detailed Python support documentation

- docs/supported-languages.md
> update cve percentage

- docs/semgrep-code/supported-languages-python.md
> Add Semgrep Code title to Python docs

- docs/faq.md
- docs/supported-languages.md
A minor rewriting of the message already sent.
Please ignore the commit message 🙃
> add Comparing Semgrep to Endor Labs section

- docs/deployment/deployment-checklist.md
> add Azure DevOps to required permissions list

- docs/semgrep-code/supported-languages-python.md
- src/components/reference/_supported-libraries-python-table.md
> Move Python libs table to seperate component

- docs/faq.md
> update info on Semgrep v Snyk

- docs/writing-rules/pattern-syntax.mdx
> fix Go example not working

- docs/semgrep-assistant/overview.md
updates based on [these changes from the Assistant team](https://docs.google.com/document/d/19P_xHPZTM-hTw4pBBWRJDj3c34xTyfG7h5xWzxI3JGU/edit?usp=sharing)
> update Privacy and legal considerations for Assistant

- docs/semgrep-assistant/getting-started.md
Update number of runs for paid and free
From [Slack thread](https://semgrepinc.slack.com/archives/C05FM4JMX2S/p1726599174794339)
> Update assistant runs

- docs/deployment/primary-branch.md
- src/components/concept/_findings-default-view.mdx
> update findings count is now consistent

- docs/getting-started/quickstart-sms.md
- docs/getting-started/quickstart.md
- sidebars.js
To understand the rationale of a second quickstart doc, please see:
https://linear.app/semgrep/issue/TEC-123/onboarding-now-with-sms
**The approach outlined above is open for discussion.**
I opted not to use any as they may get stale very quickly (i.e. we iterate a lot on the onboarding process; in fact our CI/CD docs screenshots are stale :| ) but if you think they are helpful please let me know and I'll add some.
> quickstart - managed scan

- docs/semgrep-ci/network-broker.md
> [SSC] move info re: multiple config files

- docs/deployment/deployment-checklist.md
- src/components/concept/_ip_addresses.mdx
- src/components/procedure/_receive-comments-scm.mdx
Ensures that we only have 1 source of truth for those IP addresses, and includes the cloud front IP addresses everywhere we need to show it.
> simplify ip addresses

- docs/semgrep-ci/ci-environment-variables.md
I ran into a situation that suggested that it would be useful to clarify what the display name does and doesn't do, and while in the doc, I saw some other refinements worth making.
> More context and small corrections for some environment variables

- docs/semgrep-ci/network-broker.md
> update requirements for network broker

- docs/writing-rules/data-flow/constant-propagation.md
> Update constant-propagation.md to state what we actually support

- docs/faq.md
- docs/kb/semgrep-code/language-version-support.md
- docs/supported-languages.md
> Support for all versions of a programming language

- copy-metrics-md
> Change source of metrics page to reflect renamed file in Semgrep repository

- docs/release-notes/latest.md
- docs/release-notes/september-2024.md
- sidebars.js
[Preview](https://deploy-preview-1780--semgrep-docs-prod.netlify.app/docs/release-notes/september-2024)
-----
> September 2024 release notes

- docs/supported-languages.md
> update Kotlin info in Supported Languages table + other minor updates

- docs/deployment/add-semgrep-to-ci.md
- docs/deployment/managed-scanning.md
- docs/semgrep-appsec-platform/dashboard.md
- src/components/procedure/_delete-a-project.md
> componentized removing a project

- docs/getting-started/quickstart.md
[See the Slack thread.](https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1719502852101119)
> add link to alternative scan options

- docs/semgrep-code/editor.md
> network broker not supported for code search

- sidebars.js
> Update metrics page title

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
- docs/supported-languages.md
Previews:
- [Supported Languages: Semgrep Supply Chain](https://deploy-preview-1790--semgrep-docs-prod.netlify.app/docs/supported-languages#semgrep-supply-chain)
- [Generating Python lockfiles for Semgrep Supply Chain scans](https://deploy-preview-1790--semgrep-docs-prod.netlify.app/docs/kb/semgrep-supply-chain/ssc-python-lockfiles)
> Python requirements.txt updates

- docs/ignoring-files-folders-code.md
Update table to make the order work and get the details just right, remove stale known issue.
In this case I'm asserting myself as the SME since I tested this yesterday. :)
> Update ignores table: change order, refine descriptions

- docs/usage-and-billing.mdx
> Update license and contributor count

- docs/extensions/semgrep-vs-code.md
- docs/semgrep-appsec-platform/jira.md
- docs/semgrep-code/triage-remediation.md
> update with note to api endpoints

- docs/semgrep-assistant/getting-started.md
[Preview](https://deploy-preview-1809--semgrep-docs-prod.netlify.app/docs/semgrep-assistant/getting-started#use-your-ai-provider)
> add instructions for using Azure OpenAI with Assistant

- src/components/reference/_supported-languages-table.mdx
> we support csharp 7 for community

- docs/deployment/teams.md
While the docs did have a table, it wasn't emphatic enough (see [linear](https://linear.app/semgrep/issue/TEC-211/update-documentation-to-clarify-page-or-feature-access) + attached conversations for context).
> Emphasize and explicitly state permissions for policies

- docs/supported-languages.md
[Preview](https://deploy-preview-1821--semgrep-docs-prod.netlify.app/docs/supported-languages#semgrep-supply-chain)
> update footnote marker

- docs/semgrep-appsec-platform/dashboard.md
A tiny PR a day keeps the large rewrite at bay... or something.
> add teams filter

- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
> Update troubleshooting guide step to mention max log list entries update requirement

- docs/semgrep-ci/network-broker.md
- added info on multiple instances and using a single config per deployment
- token scopes info has been added to SCM docs at an earlier date
> update Broker info

- docs/kb/rules/using-pattern-not-inside.md
> remove video that's now private

- docs/index.md
- docs/supported-languages.md
> scala is ga

- docs/semgrep-code/findings.md
- docs/semgrep-secrets/getting-started.md
- docs/semgrep-supply-chain/triage-remediation.md
> add info re: component tags to Secrets, Supply Chain docs

- docs/index.md
In addition to latest we now have to update index every month
> Update index.md for latest release notes

- docs/deployment/managed-scanning/gitlab.md
> update prereqs for GitLab SMS

- docs/kb/semgrep-supply-chain/exclude-rule.md
> add doc on how to exclude an SSC rule

- docs/deployment/deployment-checklist.md
> clarify info re: IP addresses and Network Broker

- docs/semgrep-assistant/privacy.md
Tiny quick win, as per request in [Slack](https://semgrepinc.slack.com/archives/C0370TA46PL/p1730910904100409?thread_ts=1730907496.117979&cid=C0370TA46PL)
@r2c-david You will notice that the doc itself (not the pdf) has also been updated recently to be more generalized, as we are using more AI providers now.
> update privacy with link to pdf

- docs/support.md
Slightly out of date with respect to staffing changes, the hours on [this page](https://semgrep.dev/resources/customer-success/) are current.
> Update support hours

- docs/index.md
- docs/supported-languages.md
> move Swift to GA for SSC

- src/components/reference/_admonition-sot-cves.md
[Context](https://semgrepinc.slack.com/archives/C032JB2HRDK/p1733134144372029)
> convert SSC admonition to stand-alone section

- docs/index.md
- docs/release-notes/latest.md
- docs/release-notes/november-2024.md
- sidebars.js
> November 2024 release notes

- docs/deployment/managed-scanning/github.md
> add note about SMS skipping LFS

- docs/kb/semgrep-ci/trigger-diff-scans-env-var.md
- src/components/concept/_next-steps-comments.mdx
> Fixes to info re: diff-aware scans

- docs/semgrep-appsec-platform/json-and-sarif.md
> fill out desc

- docs/semgrep-supply-chain/dependency-search.md
- docs/semgrep-supply-chain/getting-started.md
> add access note to lockfileless

- docs/semgrep-appsec-platform/json-and-sarif.md
update the json/sarif export fields
> Small changes to export field docs for accuracy on 1.101.0

- docs/kb/semgrep-ci/jenkins-diff-scans.md
- docs/kb/semgrep-ci/trigger-diff-scans-env-var.md
Jenkins is challenging to configure because there are so many options. The new KB entry covers a scenario with GitHub as a source and a Multibranch pipeline.
I also applied some updates to the general diff scans KB for clarity and consistency with the Sample CI configurations doc, and added references to the two Jenkins guides we have (as there isn't really one golden path).
When writing the Jenkins UI instructions I struggled with finding the right conventions to represent their UI elements (especially titles of sections in settings), so I would welcome feedback on how to improve that.
> [KB] Update diff scans article for consistency, add Jenkins with GH/multibranch

- docs/licensing.md
> Update License to use the new Semgrep Rules License

- docs/ignoring-files-folders-code.md
> update semgrepignore in app with correct flow

- docs/index.md
- docs/release-notes/december-2024.md
- docs/release-notes/latest.md
- sidebars.js
- src/components/procedure/_export-findings-csv.md
> add december 2024

- docs/faq.md
> Update License Info in FAQ

- docs/kb/semgrep-appsec-platform/api-404-token-scope.md
I don't expect a ton of folks to read this proactively, but it'll make it easier for us to answer questions, and it'd be great if even a few people used it to self-serve. :)
> [KB] Add guide for handling API 404s

- docs/semgrep-supply-chain/policies.md
- sidebars.js
> create a new policies page

- docs/semgrep-supply-chain/dependency-search.md
> add info on dependency path pnpm support

- docs/semgrep-appsec-platform/tags.md
> Update instructions for adding or removing tags in a project

- docs/kb/semgrep-appsec-platform/inline-pr-comments.md
- docs/kb/semgrep-appsec-platform/missing-pr-comments.md
- docs/kb/semgrep-ci/ci-vs-cli.md
- docs/kb/semgrep-ci/github-reusable-workflows-semgrep.md
- docs/kb/semgrep-ci/github-upload-findings-in-security-dashboard.md
- docs/kb/semgrep-ci/using-nonroot-docker-image-with-gha.md
- docs/kb/semgrep-ci/why-duplicate-findings.md
- src/components/procedure/_scan-with-sms.mdx
Also fixed some minor issues I saw similar to Atul's.
> fix tagging - consistently prefer semgrep in ci

- docs/writing-rules/experiments/project-depends-on.md
Based on https://github.com/semgrep/semgrep/blob/bb961637ab2eb743fb92a6c5d6207fa2c9dcf757/cli/src/semdep/subproject_matchers.py#L16
> Update list of files used to scan dependencies from

- docs/semgrep-appsec-platform/json-and-sarif.md
> clarify where line numbers are

- docs/semgrep-assistant/metrics.md
> move data from internal to user feedback dataset

- docs/semgrep-supply-chain/getting-started.md
- docs/semgrep-supply-chain/policies.md
> update ssc policies with note on default behavior

- docs/deployment/teams.md
[Preview](https://deploy-preview-1933--semgrep-docs-prod.netlify.app/docs/deployment/teams#operations-permitted-per-role)
> fix operations permitted per role table

- docs/semgrep-ci/network-broker.md
[Preview](https://deploy-preview-1936--semgrep-docs-prod.netlify.app/docs/semgrep-ci/network-broker#create-the-config-file)
> update broker docs to remove publicKey, allowedIps, heartbeat

- docs/kb/rules/rule-file-perf-principles.md
fixes https://github.com/semgrep/semgrep-docs/issues/1928. confirmed via CLI docs.
> fix default timeout value

- src/components/reference/_supported-languages-ce.md
Please stamp and go ahead and **merge** this if possible.
> supported languages fix link

- docs/kb/rules/pattern-parse-error.md
> Update markdown stlying to YAML for better syntax highlighting

- docs/kb/semgrep-ci/scan-monorepo-in-parts.md
> Update monorepo scanning with historical secrets note

- docs/semgrep-appsec-platform/jira.md
> add bit about multiple labels (xs size)

- docs/deployment/managed-scanning/overview.md
Was announced back in Nov, updating the doc accordingly.
> GL SMS is in public beta

- docs/getting-started/cli.md
> fix timeout typo

- docs/writing-rules/experiments/join-mode/overview.md
This was moved behind login with the OSS/CE change, but that didn't get picked up into this article.
> Join mode requires login

- docs/semgrep-appsec-platform/slack.md
This version of inviting is a bit more technical, but is a lot less cluttery for folks already in the channel.
~- [ ] A subject matter expert (SME) reviews the content~ xs PR, I confirmed this works in my own Slack instance
> Use the Slack command syntax for inviting

- docs/deployment/sso.md
I swear we used to have a note for this, so adding it back. It's important for people to understand that Semgrep doesn't do any separate user provisioning/management right now.
> Users managed on IdP

- algolia-config.json
Builds successfully, **merge at will**.
> update algolia config to include idp and ide tolerance (quick win)

- docs/semgrep-assistant/privacy.md
> Add a note about data co-mingling

- docs/deployment/managed-scanning/overview.md
- docs/getting-started/quickstart-sms.md
- src/components/reference/_sms-support.mdx
Everything is in public beta, and I put the info into a component. I also had to modify the Overview page a bit so things displayed normally.
* [SMS Quickstart](https://deploy-preview-1961--semgrep-docs-prod.netlify.app/docs/getting-started/quickstart-managed-scans#supported-source-code-managers)
* [SMS Overview](https://deploy-preview-1961--semgrep-docs-prod.netlify.app/docs/deployment/managed-scanning/overview#feature-maturity-and-support)
> update SMS support status based on SCM

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
- docs/semgrep-supply-chain/setup-maven.md
- docs/troubleshooting/semgrep-app.md
No actual .github/workflows .yaml file uses ubuntu-20.04, so we are good on that front.
> update to ubuntu-latest

- docs/deployment/managed-scanning/bitbucket.md
- docs/deployment/managed-scanning/overview.md
- docs/getting-started/quickstart-sms.md
- sidebars.js
> Adding bitbucket sms page and to quickstart

- docs/faq.md
> Add Opengrep to FAQ

- docs/semgrep-appsec-platform/gitlab-mr-comments.md
> fixed GitLab capitalization

- docs/faq/comparisons/codeql.md
- docs/faq/comparisons/endor-labs.md
- docs/faq/comparisons/opengrep.md
- docs/faq/comparisons/snyk.md
- docs/faq/comparisons/sonarqube.md
- docs/faq/overview.md
- docs/release-notes/april-2024.md
- docs/release-notes/march-2023.md
- docs/usage-and-billing.mdx
- docusaurus.config.js
- sidebars.js
> Break out comparison FAQ content into subpages

- docs/kb/integrations/wiz.md
> show Wiz doc in sidebar

- docs/semgrep-ci/ci-environment-variables.md
I've never been very happy with the previous wording as it doesn't have the right implications, so I wrote something longer.
> Clarify wording for baseline commit

- docs/deployment/connect-scm.md
- docs/deployment/create-account-and-orgs.md
- docs/semgrep-appsec-platform/azure-pr-comments.md
> change mentions of ADO organization to project

- docs/deployment/teams.md
> Add permissions for assistant features

- docs/semgrep-ci/network-broker.md
During training for CS we discussed whether allowing this was serving folks now that we know a bit more about the contention issues and decided we should not recommend it.
> No to multiple brokers for now 😢 

- src/components/reference/_sms-support.mdx
> update SMS support to include Bitbucket

- docs/support.md
> support.md - follow style guide, add tip

- docs/deployment/connect-scm.md
> BBDC expects http access token

- docs/kb/semgrep-code/language-version-support.md
> Update language-version-support.md with current review cycles

- docs/deployment/teams.md
- It is intentionally short for now. We'll make separate PRs as the features are shipped.
> add my teams view beta

- docs/semgrep-code/overview.md
Caught this stray OSS in the wild!
> Update overview.md - OSS to CE

- docs/semgrep-supply-chain/malicious-dependencies.md
> update maldeps with pm request

- docs/getting-started/cli-oss.md
- docs/getting-started/cli.md
- src/components/reference/_scan-ruleset.mdx
See https://linear.app/semgrep/issue/TEC-297/update-cli-local-scans for details
> corrections in CLI scans documentation

- docs/kb/semgrep-ci/collect-gitlab-logs.md
> [xs size] update line

- docs/ignoring-files-folders-code.md
> add info on global and per-project ignore paths being additive

- README.md
> [nano] We use docusaurus 3

- docs/trophy-case.md
> added CVE-2025-29783 to trophy case #2052

- docs/semgrep-appsec-platform/webhooks.md
> update callout for slack vs webhooks

- docs/extensions/semgrep-intellij.md
- docs/extensions/semgrep-vs-code.md
- docs/semgrep-pro-vs-oss.md
> Update semgrep-vs-code.md with explicit mention of license

- docs/supported-languages.md
> update lockfile info for Swift

- docs/contributing/semgrep-core-contributing.md
I'm planning to update Semgrep to 5.3.0 shortly. It already builds with 5.3.0 so we can merge this whenever.
> Update contributing instructions for OCaml 5.3

- docs/kb/semgrep-ci/new-scm-connections.md
[Preview](https://deploy-preview-2080--semgrep-docs-prod.netlify.app/docs/kb/semgrep-ci/new-scm-connections)
> add info on SCM backfill

- docs/semgrep-appsec-platform/webhooks.md
> chore(integration): [FS-2006] Webhook integration doc updates

- docs/release-notes/october-2024.md
- docs/semgrep-assistant/customize.md
- docs/semgrep-assistant/overview.md
- [Reliability](https://deploy-preview-2086--semgrep-docs-prod.netlify.app/docs/semgrep-assistant/overview#reliability)
- [Select your AI providers](https://deploy-preview-2086--semgrep-docs-prod.netlify.app/docs/semgrep-assistant/customize#select-your-ai-provider)
> update info about assistant model providers

- docs/deployment/managed-scanning/overview.md
[Preview](https://deploy-preview-2081--semgrep-docs-prod.netlify.app/docs/deployment/managed-scanning/overview#code-security-measures)
> add info re: code security measures for SMS

- docusaurus.config.js
- package.json
- yarn.lock
> Update @markprompt/docusaurus-theme-search to 0.32.4 and add its chat config

- docs/semgrep-supply-chain/malicious-dependencies.md
> Update malicious-dependencies.md to show public beta

- docs/contributing/semgrep-core-contributing.md
- docs/kb/semgrep-ci/bitbucket-jenkins-freestyle-projects.md
- docs/kb/semgrep-ci/bitbuket-jenkins-pipeline-projects.md
- docs/semgrep-appsec-platform/wiz.md
> xs: change requirements to prerequisites

- docs/semgrep-code/editor.md
- docs/semgrep-code/overview.md
- docs/semgrep-code/policies.md
- docs/semgrep-code/triage-remediation.md
This PR increases the cross-linking between Assistant and Code docs.
> add mentions of Assistant to Code docs

- docs/writing-rules/rule-syntax.md
> docs: initial `metavariable-name.module{,s}`

- docs/kb/semgrep-ci/trigger-diff-scans-env-var.md
- docs/semgrep-appsec-platform/gitlab-mr-comments.md
- src/components/code_snippets/_glcicd-semgrep-app-sast-dash.mdx
- src/components/code_snippets/_glcicd-semgrep-app-sast.mdx
- src/components/code_snippets/_glcicd-semgrep-app-ssc.mdx
> remove mentions of providing a GitLab PAT in CI configs

- algolia-config.json
> add jira as a term

- sidebars.js
> delete extraneous header

- docs/semgrep-ci/network-broker.md
> warn about performance impact of logging broker request/response bodies indefinitely

- src/components/reference/_supported-languages-table.mdx
> minor update to lang table

- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
> Clarify that --time is only a `scan` argument

- docs/semgrep-supply-chain/policies.md
This is related to SECW-3101 and https://github.com/semgrep/semgrep-app/pull/20600
> chore(automations): Add "no reachability analysis" as automation condition

- docs/semgrep-supply-chain/getting-started.md
- docs/supported-languages.md
- [Here's the table with lockfileless scanning](https://deploy-preview-2131--semgrep-docs-prod.netlify.app/docs/supported-languages#feature-support)
- [Here's the updated description of languages in the section](https://deploy-preview-2131--semgrep-docs-prod.netlify.app/docs/semgrep-supply-chain/getting-started#scan-a-project-without-lockfiles-beta)
> update with additional languages for lockfileless beta

- docs/index.md
- release-notes/april-2025.md
- release-notes/march-2025.md
[Preview](https://deploy-preview-2129--semgrep-docs-prod.netlify.app/docs/release-notes/april-2025)
> April 2025 release notes

- docs/deployment/managed-scanning/github.md
Users don't create the public app, so this rephrase helps clarify that part is installing and the private app is the creating.
> Reword so we're not suggesting creating a public app

- docs/getting-started/scm-support.md
- sidebars.js
[Preview](https://deploy-preview-2135--semgrep-docs-prod.netlify.app/docs/getting-started/scm-support)
> add doc on supported SCMs and plans

- docs/semgrep-assistant/customize.md
> Add azure openai model advice

- docs/contributing/adding-a-language.md
This updates file paths that had become incorrect and rephrases some of the instructions to be more explanatory and more robust to future changes.
This is a quick unplanned update to unblock a user-contributor. I only fixed what seemed urgent and obvious. I don't claim that everything in this document is still up-to-date.
> Update the instructions to start the integration of a new language

- docs/semgrep-supply-chain/getting-started.md
> return accidental loss

- docs/deployment/teams.md
Still need to update the first image in the article.
> update teams terminology to match product

- docs/usage-and-billing.mdx
> Update usage-and-billing.mdx to have 90 day rolling interval

- docs/semgrep-appsec-platform/jira.md
Fixed and removed findings don't require action to address, so they don't support Jira ticket creation.
> Clarify that Jira tickets cannot be created for fixed/removed findings

- docs/semgrep-appsec-platform/webhooks.md
Customer asked about this, seemed like an easy thing to fix :)
~- [ ] A subject matter expert (SME) reviews the content~ xs PR
> Clarify SAST-only and numeric ID function

- docs/semgrepignore-v2-reference.md
- sidebars.js
> put semgrepignore v2 under experimental subfolder

- docs/semgrep-appsec-platform/github-pr-comments.md
> update screenshot (nano-size, quick win)

- docs/getting-started/scm-support.md
Generic secrets requires Semgrep Assistant, so I'm updating the support SCMs doc to reflect this.
> update supported SCMs docs

- docusaurus.config.js
- src/css/custom.scss
Updated links to match about 80% the content in the main site (where appropriate).
Match the colors used in the site.
> Updated footer 

- docs/kb/semgrep-ci/github-repository-rulesets-semgrep.md
This article has generally been aimed at setting up rulesets for a single org, this just makes it a bit more clear/explicit.
> Small clarifications about single-org usage

- docs/semgrep-code/policies.md
We had some customer and internal confusion over this, so although this isn't the desired behavior, documenting it for now should be helpful.
> Mention rule/ruleset issue in multiple policies

- docs/deployment/add-semgrep-other-ci.md
- docs/getting-started/quickstart.md
- docs/kb/semgrep-appsec-platform/error-externally-managed-environment.md
- docs/kb/semgrep-code/run-specific-version.md
- docs/semgrep-ci/sample-ci-configs.md
- docs/semgrep-code/semgrep-pro-engine-intro.md
- docs/update.md
- src/components/procedure/_install-cli.mdx
> add notes on how to handle "error: externally-managed-environment" during install/upgrade

- sidebars.js
> update link to go to Assistant enablement instructions, not overview

- docs/cli-reference.md.template
> Deprecate exit code 14

- docs/getting-started/scm-support.md
- docs/semgrep-assistant/overview.md
> Remove unsupported Assistant features for Bitbucket DC

- algolia-config.json
- docs/deployment/connect-scm.md
> search-related fixes

- docs/semgrep-assistant/metrics.md
Oh, apostrophes. How you vex people.
> Small grammar fixes for Assistant metrics page

- algolia-config.json
> update search terms: add synonym for lockfileless

- docs/kb/integrations/customize-semgrep-precommit.md
> Update customize-semgrep-precommit: Add awk example for selective output

- docs/supported-languages.md
> update docs: PHP reachability is now GA

- docs/semgrep-supply-chain/dependency-search.md
> update Python dependency path support

- docs/contributing/semgrep-contributing.md
- docs/contributing/semgrep-core-contributing.md
- docs/deployment/teams.md
- docs/semgrep-appsec-platform/gitlab-mr-comments.md
- docs/semgrep-assistant/overview.md
- docs/semgrep-supply-chain/upgrade-guidance.md
- docs/troubleshooting/semgrep.md
- release-notes/august-2022.md
- release-notes/march-2025.md
> fix broken anchors

- .github/workflows/build-and-deploy.yml
- .github/workflows/test-build.yml
the first step in upgrading Docusaurus is to upgrade Node
> upgrade node

- docs/deployment/managed-scanning/azure.md
- docs/deployment/managed-scanning/bitbucket.md
- docs/deployment/managed-scanning/github.md
- docs/deployment/managed-scanning/gitlab.md
- docs/getting-started/quickstart-sms.md
- docs/getting-started/quickstart.md
* [Quickstart preview](https://deploy-preview-2269--semgrep-docs-prod.netlify.app/docs/getting-started/quickstart)
* [SMS Quickstart preview](https://deploy-preview-2269--semgrep-docs-prod.netlify.app/docs/getting-started/quickstart-managed-scans)
> small fixes to quickstarts, including minor SMS clarifications

- docs/deployment/add-semgrep-other-ci.md
- docs/deployment/add-semgrep-to-ci.md
- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_semaphore-semgrep-app-sast.mdx
- src/components/code_snippets/_semaphore-semgrep-oss-sast.mdx
> minor edits to Semaphore example

- docs/semgrep-supply-chain/policies.md
> minor edits to SSC policies doc

- docs/semgrep-assistant/metrics.md
> Update Assistant metrics

- docs/index.md
- release-notes/august-2025.md
- release-notes/july-2025.md
[Preview](https://deploy-preview-2294--semgrep-docs-prod.netlify.app/docs/release-notes)
> August 2025 release notes

- docs/index.md
- release-notes/august-2025.md
> fix findings number for Jira tickets

- docs/semgrep-appsec-platform/scm-code-access.md
~- [ ] A subject matter expert (SME) reviews the content~ xs PR
> not two BB Clouds!

- docs/kb/semgrep-ci/jenkins-diff-scans.md
- docs/semgrep-code/glossary.md
Preview: 
* [KB](https://deploy-preview-2323--semgrep-docs-prod.netlify.app/docs/kb/semgrep-ci/jenkins-diff-scans)
* [Glossary](https://deploy-preview-2323--semgrep-docs-prod.netlify.app/docs/semgrep-code/glossary#diff-aware-scan)
> [TEC-429] Diff aware scans are not interfile

- docs/semgrep-secrets/getting-started.md
- docs/usage-and-billing.mdx
> update contact info to get Secrets licenses

- docs/deployment/add-semgrep-to-ci.md
- docs/deployment/core-deployment.md
- docs/deployment/managed-scanning/azure.md
- docs/deployment/managed-scanning/bitbucket.md
- docs/deployment/managed-scanning/github.md
- docs/deployment/managed-scanning/gitlab.md
- docs/deployment/managed-scanning/overview.md
- docs/getting-started/quickstart-sms.md
- sidebars.js
- remove all beta flags
- minor edits to sidebar to ensure that Managed Scans comes up before CI integrations
- added a note from the CI integration page to the Managed Scans page
> update Managed Scans docs in preparation for launch

- docs/running-rules.md
> add info about local rules' IDs
