- docs/extra.css
the CSS changes seem a bit brittle so I don't know if we actually want this, but it gives us a lot more space for content when I have my browser taking up 50% of my screen, which a good number of people might when reading our docs.
before then after:
> make the left navbar thinner

- docs/writing-rules/pattern-logic.md
- docs/writing-rules/pattern-syntax.md
This change helps new users who are looking at some of the more daunting reference pages be aware of the tutorial and the getting started "paved road".
> Add tutorial reference to rule references

- mkdocs.yml
By adding the redirects plugin, we now also need to specify other plugins even if they’re part of the theme and weren’t previously listed in the plugins section.
This fixes #37.
Screenshot of working search + result:
> Add search as an explicit plugin

- docs/experiments/overview.md
- docs/extra.css
- docs/writing-rules/pattern-syntax.md
- docs/writing-rules/rule-syntax.md
This is a hacky way to prevent the TOC from listing the title of its own document
Fixes #48
> Hide the TOC’s first level list item

- docs/integrations.md
(for PR comments)
This secret is automatically made available by GitHub.
> Inform the user that the secret GITHUB_TOKEN does not need to be created

- mkdocs.yml
The default minimum search length is three characters. This changes the minimum length to two characters, allowing users to search for terms like `CI` for which we have useful search results 🔍
> Allow two-character search queries

- docs/integrations.md
- using SEMGREP_REPO_NAME as env variable name
- Add CI providers for searchability of generic CI section
- document the --baseline-ref flag
closes https://github.com/returntocorp/semgrep-app/issues/1144#event-4022065994
> allow users to set project name as environment variable and document --baseline-ref

- docs/search_js.js
- mkdocs.yml
When one searches the docs and there are no results found, there may still be results available in the Semgrep Registry. This overrides the default “no results found” message with a message that includes a suggestion to go search in the Registry.
> Suggest to search the Semgrep Registry when searching docs returns no results

- docs/integrations.md
Documenting some of the external uses of semgrep, tagging maintainers in case they have an preferences on whether/where we link to:
- https://github.com/DefectDojo/django-DefectDojo/pull/2781 (@valentijnscholten)
- NodeJSScan / LibSast (@ajinabraham)
- SALUS (@ghbren)
- Dracon (@VJftw)
> link to other tools that use semgrep

- docs/integrations.md
The Buildkite example code looks like it's actually some kind of Chef DSL - `expeditor`/`executor` are not [Buildkite commands](https://buildkite.com/docs/pipelines/defining-steps)
> Fix the Buildkite pipeline example

- mkdocs.yml
Preview: ![Screen Shot 2021-02-01 at 4 09 18 PM](https://user-images.githubusercontent.com/302941/106534167-4f246280-64a8-11eb-9119-de361fef41f4.png)
Also note [this comment](https://github.com/returntocorp/semgrep-docs/issues/68#issuecomment-771259333) from @chmccreery: 
> “I like it! The sections don't all make sense to me immediately (where would I go for Semgrep Action documentation, for example?), but otherwise I am not bothered by the lower amount of nesting.
cc @underyx and @dlukeomalley
> Un-nest sidebar links to simplify nav menu, fixes #68

- custom_theme/cheat-sheet-base.html
- docs/cheat-sheets/django-xss.md
- docs/cheat-sheets/flask-xss.md
- docs/cheat-sheets/java-jsp-xss.md
- docs/cheat-sheets/rails-xss.md
shortens the CTA on all the cheatsheets
> use short link (/p) for cheatsheet configs

- docs/extra.css
As the top-navbar was added it created to bugs which are fixed by this PR, tested for mobile and desktop views: 
1. When using a ID targeted header link (either by clicking on the TOC or using an external link) the navbar hides the header from view. Adding `scroll-margin-top: 60px` fixes this issue. 
2. The left navbar is pushed down by 50px and the last link on the list is never visible. Fixing the height with `height: calc(100% - 50px);` but then the padding at the bottom acts weird. The `padding-bottom` lines makes sure that there is a padding at the end of the list which scrolls with the menu items.
> css: adding scroll-margin and height fixes for left nav

- docs/faq.md
After https://github.com/returntocorp/semgrep/pull/2562 we no longer make this network request.
> Remove '--generate-config' FAQ network request

- docs/writing-rules/rule-syntax.md
Trying to specify that a metavariable matching a string includes the quotes as part of the fix for https://github.com/returntocorp/semgrep/issues/2578
> adding specifications for metavariable-regex

- docs/experiments/overview.md
- docs/writing-rules/rule-syntax.md
`metavariable-comparison` has been hanging out in experimental for 4 months. Since then we've added it to 15 rules:
```
$ rg 'metavariable-comparison' | wc -l
15
```
My concern is that people won't find it if it's hiding under experiments, and may resort to `pattern-where-python`. Lets bring this thing out for primetime :+1:
> Promote 'metavariable-comparison' from experimental

- docs/sample-ci-configs.md
Rather than placing it in an expando-details element
Preview:
> Show the example file for GitHub Actions by default

- docs/extra.css
Code blocks with lines of a certain length currently don't wrap, causing the width of the content to expand beyond what we support for mobile devices and consequently affecting the rest of the page. This PR fixes that.
Before:
After:
> Wrap overflowing code blocks on mobile

- docs/writing-rules/testing-rules.md
For the new YAML language testing functionality, and I missed an update here when we made `--test` respect `--config`.
> Add testing rules docs on .test.yaml and separate rule/target directories

- docs/writing-rules/rule-syntax.md
Closes https://github.com/returntocorp/semgrep-docs/issues/142.
Also tries to make use of the new editor widget! If it doesn't work we can remove it.
> Add documentation for pattern-not-regex

- docs/cheat-sheets/rails-xss.md
Hi — this is a very cool project! Very trivial PR here, hope you don't mind. I showed my team the Rails XSS use case specifically, and in doing so noticed (and fixed) a typo.
> fix typo (Ruby, not Python)

- docs/sample-ci-configs.md
Read and agreed semgrep's Code of Conduct
Description:
Adapted and tweaked from @daghan https://github.com/daghan/lets-be-bad-guys (thank you again !)
Adding a simple example Jenkins CI declarative, with diff-scan enabled, in the documentation 😃
> Adding Jenkins example CI provider

- docs/writing-rules/overview.md
- docs/writing-rules/rule-ideas.md
Add embeditor widget for in-the-docs examples. Rename the title of the page to Custom rule examples to make it more explicit what the page is about.
> Update 'rule ideas' to be more specific about use cases for custom rules

- docs/writing-rules/overview.md
in simple editor.
Closes https://github.com/returntocorp/semgrep/issues/3118
> Use getting started example that doesn't have quotes that get stripped

- docs/sample-ci-configs.md
It seems to be broken in the current documentation online, there are 4 backticks to close instead of 3, which makes the Jenkins block spill into the others
You can take a look here https://semgrep.dev/docs/sample-ci-configs/#jenkins
> Fix broken markdown in example CI configs

- docs/managing-policy.md
- docs/notifications.md
- docs/semgrep-ci.md
- docs/writing-rules/rule-ideas.md
- mkdocs.yml
Made this change because CI Integrations sounds like it's about which CI providers Semgrep CI can run in. We already use "Notifications" on the main Semgrep CI docs page.
> Rename "CI Integrations" to "Notifications"

- README.md
- custom_theme/404.html
- custom_theme/base.html
- custom_theme/cheat-sheet-base.html
- mkdocs.yml
According to [this note from mkdocs](https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12):
> So long as the old "UA-" ID and new "G-" ID are properly linked in your Google account, and you are using the "G-" ID, the data will be made available in both the old and new formats by Google Analytics.
Note I’m not able to get this working locally yet. I don’t see the GA tag loading on the local page and when running in verbose mode, I see what seems to be mkdocs not picking up the new gtag configuration:
```
Loaded theme configuration for 'readthedocs' from '/usr/local/lib/python3.9/site-packages/mkdocs/themes/readthedocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'locale': 'en',
'include_search_page': True, 'search_index_only': False, 'highlightjs': True, …
```
> Remove universal analytics and add GA4 analytics

- docs/extra.css
small update to cheat sheet code examples CSS styles
before:
after:
> update cheat sheet code examples style

- custom_theme/cheat-sheet-base.html
- docs/cheat-sheets/django-xss.md
Provide an opportunity to explicitly set the language for a code example, because highlight js not always guesses it right
> update code highlighting in cheat sheets

- docs/status.md
Same order as here: https://dashboard.semgrep.dev/languages :+1:
> Add Python, OCaml, and PHP to language parse rate

- docs/cli-usage.md
Proposal for updating the CLI docs based on confusion I personally had with lack of information on exit codes as seen in this [issue ](https://github.com/returntocorp/semgrep/issues/3535)
> Updated CLI exit code docs for consistency with flags

- docs/writing-rules/rule-syntax.md
Following up on the discussion from returntocorp/semgrep#3424.
Added an example of using arithmetic and boolean operators in `metavariable-comparison` to highlight the fact that it can perform more complex expressions than just simple comparisons.
> Updated metavariable-comparison docs to include example of complex expression

- docs/cli-usage.md
- docs/contributing.md
- docs/experiments/generic-pattern-matching.md
- docs/experiments/overview.md
- docs/extensions.md
- docs/faq.md
- docs/getting-started.md
- docs/ignoring-findings.md
- docs/index.md
- docs/managing-findings.md
- docs/running-rules.md
- docs/semgrep-app/managing-policy.md
- docs/semgrep-app/notifications.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/sample-ci-configs.md
- docs/trophy-case.md
- docs/troubleshooting/gitlab-sast.md
- docs/troubleshooting/rules.md
- docs/troubleshooting/semgrep-app.md
- docs/writing-rules/overview.md
- docs/writing-rules/pattern-syntax.mdx
- docs/writing-rules/rule-ideas.md
- docs/writing-rules/rule-syntax.md
- docs/writing-rules/testing-rules.md
- docusaurus.config.js
- sidebars.js
- Prevents some meta tags being generated with URLs that have a double slash like `https://semgre.dev//docs/foo`
- Standardizes link format to prevent unnecessary redirects
- Adds experiments page to the sidebar
- Adds social card images (using the same image that’s used in the rest of semgrep.dev)
- Updates meta descriptions for several pages
> Misc bug fixes

- docs/writing-rules/pattern-syntax.mdx
Hello!
A little doc PR here.
This should be 'metavariable-regex', per my eye.
Please let me know if that's not the case and close.
> Correct typo of 'metavariable-regexp'

- docs/semgrep-app/notifications.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
- docs/semgrep-ci/sample-ci-configs.md
This removes publishDeployment and related environment variables from all of our instructions and example scripts!
> We have made publishDeployment obsolete for semgrep-action

- docs/contributing/semgrep-contributing.md
Installing semgrep using the pip on my M1 Mac resulted in getting an executable that could not actually be run. Installing with homebrew worked fine, so I've added a note about this.
> Add note that installing semgrep with pip can fail on M1 Macs

- docs/writing-rules/rule-syntax.md
Update the rules doc to specify that you will need to explicitly add your test directory to the path inclusion filter.
> Update rules doc with testing note

- docs/writing-rules/data-flow.md
A small fix so some of the tips render correctly.
> Fix admonitions

- docs/faq.md
Added a section in the FAQ about how to use the embeditor.
@pabloest If there's a better section for this, let me know! We had someone ask about how to do this during a workshop and realized we didn't have docs for this.
> Add section to FAQ about embeditor

- docs/semgrep-ci/overview.md
> Make diff scan behavior more clear

- src/css/custom.css
Originally #343 but had a CircleCI error cause accidentally I branched off a previous branch.
Changes an rgba color to hex so Firefox/Safari properly shows the dark mode background. Also moved this color from the property to the responsible variable and changed the background color to true black for the benefit of all those OLED screens.
Also Prettier cleanup on whole file.
> style: Dark mode bg fix in Firefox/Safari + Prettier

- docs/semgrep-app/notifications.md
These changes reflect the specific changes I made to `webhook.py` recently. Additionally, I am looking for evidence that the fields “category”,  “license”, “owasp”, “references”, “source”, “technology” and “vulnerability” exist in the webhook, as I don't see them anywhere in `webhook.py`. Maybe I am missing something, though!
> Update webhook to match recent deletions

- docs/contributing/semgrep-core-contributing.md
- docs/semgrep-app/notifications.md
- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
Make it clearer what the recommended setup is in terms of when diff-scans are used and when full scans are used.
We have had multiple users configure Semgrep incorrectly, and have poor experiences with the app as a result.
> Recommend diff scans and full scans on separate branches

- docs/cli-usage.md
- docs/semgrep-ci/overview.md
Once https://github.com/returntocorp/semgrep/pull/4350 is merged, the Semgrep CLI will support `.semgrepignore` files. This PR removes the warning on the Semgrep CI doc that says the CLI does not support this, and adds a section to the CLI doc that duplicates the explanation in the CI doc. Eventually we plan to remove this functionality from Semgrep CI, and when we do that we can remove the duplication in the docs.
> Update docs on .semgrepignore

- docs/extensions.md
Should help prevent issues like https://github.com/returntocorp/semgrep/issues/4310 in the future. Using this updated pre-commit hook, semgrep will not scan files with unknown file extensions during a pre-commit scan.
> Use --skip-file-extensions in the semgrep pre-commit hook

- docs/troubleshooting/semgrep.md
- sidebars.js
Rename `troubleshooting/semgrep-cli` to encompass both `semgrep-ci` and `semgrep-cli` and include information on how to get additional information from semgrep-action.
> Document how to see semgrep-ci logs

- docs/writing-rules/pattern-syntax.mdx
> pattern-syntax: Limitations of ellipsis

- docs/experiments/generic-pattern-matching.md
> generic-pattern-matching: Add ellipsis metavariables

- docs/writing-rules/rule-syntax.md
> rule-syntax: Add rule options vardef_assign and attr_expr

- docs/cli-usage.md
Semgrep always exits with code 7 if at least one rule it is passed is invalid.
> Update meaning of exit code 7

- docs/writing-rules/data-flow/taint-mode.md
> taint-mode: Explain metavariable unification and its consequences

- docs/release-notes.md
> Fix small typos in release notes v 0.77.0

- docs/release-notes.md
> Remove repeated month in release notes

- docusaurus.config.js
For linking to issue regarding redirects.
> update cli reference redirect

- docs/writing-rules/data-flow/constant-propagation.md
> constant-propagation: Explain $MVAR comparisons and mutable objects

- copy-default-semgrepignore.py
- docs/cli-usage.md
- docs/semgrep-ci/overview.md
- package.json
The CLI now uses a default `.semgrepignore` file
> Update information about default semgrepignore behavior

- docs/troubleshooting/semgrep.md
We now save the rules run by semgrep in the semgrep action logs. Update the docs to reflect this
> Document that we log the rules run by semgrep

- docs/ignoring-findings.md
This is tied to the release of https://github.com/returntocorp/semgrep/pull/4535 (semgrep 0.79 if PR is accepted promptly)
> Update the documentation for nosemgrep

- docs/experiments/symbolic-propagation.md
- docs/writing-rules/pattern-syntax.mdx
- docs/writing-rules/rule-syntax.md
- sidebars.js
And fix links to constant propagation.
> experiments: Add symbolic propagation

- docs/writing-rules/rule-syntax.md
I based the extensions on common ones found online. I based the tags on the Playground and on semgrep-core/src/core/ast/Lang.ml.j2 and grepping around semgrep-core.
R and hack don't seem to have a value in Playground? I assume it's [r] for R and [hack] for hack, but would love to know what file to definitively answer my question.
> added missing tags

- Makefile
- docs/contributing/semgrep-core-contributing.md
test plan:
yarn start and see http://localhost:3000/docs/contributing/semgrep-core-contributing
> document --dump-command-for-core

- docs/experiments/project-depends-on.md
Updates the `project-depends-on` docs to describe the required keys, and adds a table specifying the relationship between languages, namespaces, and lockfiles.
Depends on: https://github.com/returntocorp/semgrep/pull/4699
> Update project depends on docs

- docs/extensions.md
I'm updating the capitalization of Scanmycode to ScanMyCode after receiving feedback that `scanmy` was mistaken for `scammy`. This doesn't match the capitalization used by the underlying project, but I think is a valuable change given that these are Semgrep-hosted docs for our user base.
@marcinguy, are you comfortable with this change based on concerns on how it reads?
> Capitalize ScanMyCode

- docs/experiments/metavariable-analysis.md
- sidebars.js
Fixes for examples based on community feedback
entry for `metavariable-analysis` in sidebar
> fix: metavar-analysis discoverability

- docusaurus.config.js
because GA4 lacks many features of Universal Analytics, and UA will still be around for another ~18 months
> Add Google Anayltics (Universal Analytics)

- docs/release-notes.md
These characters were probably generated by https://word2md.com/
> Fix escape and other weird characters in release notes

- .github/workflows/markdown-link-check-on-schedule.yml
- .github/workflows/markdown-link-check.yml
- .mlc_config.json
- README.md
- docs/experiments/join-mode/recursive-joins.md
- docs/experiments/overview.md
- docs/ignoring-files-folders-code.md
- docs/status.md
This PR squashes a few broken links. It also updates the Markdown link checker so that it’s more reliable and, besides checking every PR, so it also runs once weekly to help prevent link rot.
> Squash broken links

- docs/status.md
Scala was recently officially promoted to GA: https://github.com/returntocorp/semgrep/pull/4973
> List Scala as GA

- docs/writing-rules/data-flow/taint-mode.md
Fix to use actual url instead of localhost.
> docs(taint-mode): fix link

- docs/index.md
- docs/status.md
As a side-effect, this alphabetizes Scala before TS/TSX.
I almost missed Scala support because it was below TypeScript, then found that `index.md` had been updated and this one hadn't.
> Sync language support status with index page

- docs/contributing/semgrep-contributing.md
`sudo pip install` can cause some file ownership and permissions issues. Removed the line and swapped it out with contact info to reach out to in case of issues (recommended by @underyx).
> Remove `sudo pip install` in contributing docs

- docs/status.md
User-defined equivalences have been deprecated for a long time,
so equivalence_eq is not relevant anymore
test plan:
nope
> remove equivalence_eq from maturity

- docs/writing-rules/rule-syntax.md
Changes:
* new behavior of `^` and `$` brought by the multiline mode, starting with the next Semgrep release (0.95). The change was approved by @annikalee and @mjambon and is documented in Semgrep's changelog.
* fix incorrect mention of compatibility with Python's `re` rather than PCRE (we switched to PCRE a while ago)
> Update the documentation ahead of Semgrep 0.95 regarding regexp matching

- README.md
- package.json
This PR creates a `yarn dev` command which is identical to yarn start without running the replacements script. Use when developing docs. Run `yarn start` if you want to see the final form of the docs (with replacements).
> added yarn script dev to prevent replacements script

- docs/semgrep-ci/configuration-reference.md
Resolves: https://linear.app/r2c/issue/MKT-365/document-ci-handling-fail-open-and-fail-closestates
> Add fail open, fail close mention

- .github/workflows/markdown-link-check.yml
The mentioned issue was fixed upstream and the 'with:' was accidentally removed which causes run issues now. Fixed both and lifted the version pin (on @v1 no breaking changes should happen).
> Fix and revert markdown-link-check.yml

- docusaurus.config.js
because GA can now be handled by Google Tag Manager (GTM)
> Remove the default Google Analytics plugin

- docs/semgrep-ci/sample-ci-configs.md
Updated sample CI configuration for Buildkite after doing some testing and adding official integration support into the app.
Opted for no highlighting due to the funky pound sign highlighting:
> Updated sample CI configuration for Buildkite

- docs/experiments/extract-mode.md
Corresponds to changes from: <https://github.com/returntocorp/semgrep/pull/5749>
> Allow `generic` for extract mode

- docs/index.md
> Remove Semgrep CI as a separate Semgrep ecosystem

- docs/writing-rules/rule-syntax.md
**What:**
Currently, the `pattern-inside` example isn't super insightful into what `pattern-inside` actually changes.
**Why**:
This is because it shows off an example where the `pattern` would match regardless of whether the `pattern-inside` rule were to be there. I think the strength of `pattern-inside` is in showing what examples _should not_ match, if a user were to use it. For reference, this confused me over why I should use `pattern-inside`, or care about it.
**How**:
I added a `def foo` which has a `return` which is unmatched, as a result of not being in a `class`.
> change(writing-rules): clarify pattern-inside example

- docs/experiments/generic-pattern-matching.md
This was prompted by https://github.com/returntocorp/semgrep/issues/5665
> Add a tutorial on how to deal with line-based formats in generic mode

- docs/writing-rules/rule-syntax.md
pathlib doesn't match `**/*` but wcmatch (which semgrep uses) does so update links and add an example to clarify
> Update docs to point to wcmatch

- docs/writing-rules/rule-syntax.md
Fix rule_schema.yaml link in rule-syntax.md to reflect the file move in https://github.com/returntocorp/semgrep/commit/ba08b088afb6aa7ad5ca975803f4da95fd590201
> Fix rule_schema.yaml link in rule-syntax.md

- docs/writing-rules/rule-syntax.md
> Fix header of `patterns` operator evaluation strategy

- src/components/reference/_supported-languages-table.mdx
As of https://github.com/returntocorp/semgrep/pull/5870, Swift meets the bar for experimental status!
> Change Swift to experimental

- docs/contributing/contributing-code.md
This goes with the [updated semgrep PR template](https://github.com/returntocorp/semgrep/pull/5962).
> Add a new section "explaining" code and update changelog management.

- docs/experiments/generic-pattern-matching.md
I wasn't sure about the internal link so I used the full URL https://semgrep.dev/docs/writing-rules/rule-syntax/#options. Maybe an internal link is better (= less likely to change when the server name changes).
> Update generic examples + how to ignore comments

- docs/semgrep-ci/sample-ci-configs.md
PR to improve the sample ci config for circle CI. Gave comments on what the variable groups so as well as adding the SEMGREP_REPO_NAME variable to get auto-set rather than needing to set it manually.
- [ x] A subject matter expert (SME) reviews the content
- [x ] This change has no security implications or else you have pinged the security team
- [x ] Redirects are added if the PR changes page URLs
> updated circleci yaml

- docs/contributing/contributing-code.md
This adds a section on how to avoid common problems with submodules.
> Add guidelines to deal with submodules

- docs/writing-rules/rule-syntax.md
Added a change to document the support for `not in` in `metavariable-comparison`
> chore: document not-in

- docs/semgrep-app/integrations.md
With the deprecation of Zendesk on our side this link should also be removed from the docs as it is also deprecated. 
* [Integrating Semgrep with webhooks](https://support.semgrep.dev/hc/en-us/articles/4415975269275-Integrating-Semgrep-with-Webhooks)
> Remove the 'Integrating Semgrep with webhooks link

- docs/writing-rules/testing-rules.md
If we do not import secure_eval in detect-eval.py, then there will be a difference between detect-eval.py and detect-eval.fixed.py. This would result in the following out of the command `semgrep --test --config tests/rules/ tests/targets/`:
```
1/1: ✓ All tests passed
0/1: 1 fix tests did not pass:
--------------------------------------------------------------------------------
✖ tests/targets/python/detect-eval.fixed.py <> autofix applied to tests/targets/python/detect-eval.py
---
+++
@@ -1 +1 @@
-from lib import get_user_input, safe_get_user_input, secure_eval
+from lib import get_user_input, safe_get_user_input
```
> Added import of secure_eval in detect-eval.py

- docs/semgrep-ci/sample-ci-configs.md
Fixed the ["Alternate job that uploads findings to GitHub Advanced Security Dashboard"](https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions) sample CI files to actually upload the SARIF files to the dashboard. With the current command they do not upload any findings as a SARIF file is never created. This is to be more inline with: 
https://semgrep.dev/docs/semgrep-ci/running-semgrep-ci-with-semgrep-app/#setting-up-security-dashboards-for-github-and-gitlab 
GitHub file which does upload the findings.
> Fix sample-ci-configs.md's uploading findings file

- docs/experiments/autofix.md
- docs/experiments/deprecated-experiments.md
- docs/experiments/introduction.md
- docs/semgrep-app/notifications.md
- docusaurus.config.js
- sidebars.js
> Split overview of Experiments category to Autofix and Deprecated experiments, add introduction

- docusaurus.config.js
> Fix redirects in experimental category and release notes

- docs/semgrep-app/getting-started-with-semgrep-app.md
Update 'Getting started with Semgrep App' docs to include the permission of API permission scope. This is based on trying to login with GitLab.
> Update Semgrep App starting docs

- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/sample-ci-configs.md
Change to the SEMGREP_TIMEOUT variable, as it was slightly out-of-date in the docs. Update the CI reference to reflect its actual behavior, and removed SEMGREP_TIMEOUT from the sample snippets as it is no longer a flag.
I did add DEFAULT_TIMEOUT into the snippets by default, as since it is not a general timeout for the entire semgrep job, rather a timeout per-file, it seems like less of a general customization and more of a niche tweak one would use if one or a few files happen to be taking too long to scan. Will defer to Emma on if this should be added in the default snippets.
- [x ] This change has no security implications or else you have pinged the security team
- [x ] Redirects are added if the PR changes page URLs
> Updating Semgrep timeout docs

- docs/semgrep-ci/configuration-reference.md
> renamed default_timeout to correct semgrep_timeout

- docs/release-notes/october-2022.md
Move update about Bloom filter optimization to general CLI changes in release notes as it is not related to Taint mode
> Fix release notes - Disabled Bloom filter is general CLI change

- docs/contributing/semgrep-core-contributing.md
- docs/release-notes/july-2022.md
- docs/semgrep-app/getting-started-with-semgrep-app.md
- docs/semgrep-app/notifications.md
- docs/writing-rules/testing-rules.md
- src/components/procedure/_enable-autofix.mdx
> Remove autofix enablement info from Projects page, modularize enabling autofix and import it to more docs

- docs/writing-rules/pattern-syntax.mdx
This feature is implemented for some languages but not all of them. It's a natural expectation from users, so we try to support it when it doesn't cause problems, even if it's redundant with metavariables.
> A word about ellipses matching non-sequences

- src/components/reference/_ci-ignoring-files.mdx
This previously linked to `.semgrepignore` file that is used when Semgrep scans the Semgrep repository, so it has things specific to scanning Semgrep in there. I've updated it to link to the default `.semgrepignore` that Semgrep uses when scanning anything if there is no `.semgrepignore` file provided by the user.
> Update .semgrepignore link

- docs/ignoring-files-folders-code.md
Adjusting --include behavior as it does not override the gitignore/semgrepignore files.
> Adjust --include behavior to not override ignores

- docs/deepsemgrep/deepsemgrep-introduction.md
Updated the commands to run --interfile, instead of --deep.
> Changed to --interfile tag

- docs/cli-reference.md
Add in the new flags for scan
Question: is there an equivalent ci reference to add?
Test plan: compare to `semgrep scan --help`
> chore: Update the semgrep scan help text

- docs/semgrep-ci/overview.md
Changed the path of the link to the following info box:
Semgrep Cloud Platform creates a SAST (Static Application Security Testing) job by default. To run dependency scans exclusively, refer to Sample CI configurations. 
As the link to the Sample CI configurations was broken. The link currently leads to [https://semgrep.dev/docs/semgrep-ci/overview/semgrep-ci/sample-ci-configs/](https://semgrep.dev/docs/semgrep-ci/overview/semgrep-ci/sample-ci-configs/) which does not exist.
> Changed path of Sample CI configs doc due to broken link

- docs/release-notes/february-2023.md
Please check this small update. I think that this is something I initially had in mind, but when reading this section of release notes again, I realized it does not really convey the meaning I wanted (without this fix, it might be even confusing for readers - 1. Semgrep CLI is renamed. 2. You can still use Semgrep CLI - it does not make logical sense without what we internally know here).
> Update february 2023 release notes

- docs/getting-started.md
From what I've seen, most tools do a version check to confirm installation instead of running a pattern. While it is nice to see a scan, I worry the syntax is a bit jarring on first impression. What do folks think?
- [] A subject matter expert (SME) reviews the content
- [] Redirects are added if the PR changes page URLs
> check version to confirm installation

- docs/semgrep-ci/sample-ci-configs.md
There is a reference to Bitbucket in the Buildkite section of "Sample CI configurations" - it should probably just refer to Buildkite.
> Fix reference to Bitbucket in BuildKite section

- docs/writing-rules/data-flow/constant-propagation.md
- docs/writing-rules/rule-syntax.md
This is only to make some links consistent. These updates might help once we need to bulk find and replace many links in the future.
> Consistency link update (absolute paths relative to /docs/)

- docs/supported-languages.md
- docs/writing-rules/experiments/project-depends-on.md
We no longer us `go.sum` files to detect dependencies in go projects, we use `go.mod`. We can also identify transitive dependencies now.
> Reflect switch to `go.mod`

- docs/semgrep-code/semgrep-pro-engine-intro.md
* removed the section on interprocedural (it's now included by default in Semgrep Pro Engine)
* combined the section about performance differences into a general analysis heading
> interprocedural enabled by default on PRs

- docs/semgrep-code/semgrep-pro-engine-intro.md
*missing a <dl> tag caused this section to show up as a code snippet
> Remove additional space that causes break in the description list

- docs/faq.md
- docs/licensing.md
This should be "Commons Clause":
- https://github.com/returntocorp/semgrep-rules/blob/develop/LICENSE
- https://commonsclause.com/
> Common Clause -> Commons Clause

- docs/semgrep-ci/configuration-reference.md
- docs/semgrep-ci/overview.md
- docs/semgrep-cloud-platform/getting-started.md
- docs/semgrep-cloud-platform/scm.md
- docs/semgrep-cloud-platform/user-management.md
- docs/semgrep-code/findings.md
- docs/semgrep-code/getting-started.md
- docs/semgrep-code/semgrep-pro-engine-intro.md
- src/components/procedure/_platform-add-repo.md
- src/components/reference/_triage-states.mdx
See the ff tables for the changes:
`docs/semgrep-ci/configuration-reference`
* Corrected from `semgrep ci` to `semgrep ci --config p/default` to bypass login for the specific use case of testing environment (CI) variables. (It's tested folks.)
`docs/semgrep-code/getting-started`
|  OLD | NEW  |
| ------ | ------ |
| SAST (Static Analysis...) | Fixed as "SAST (Static **Application**...)" |
| Previously stated this getting started doc is only for paid tiers. This is not accurate | The Semgrep Code doc actually covers features for both free and paid, and it's a tofu doc, so it should be more welcoming with some intro to the value add of paid tiers |
| OSS and Code table comparison is above the fold | Moved the comparison table of OSS and Code after scanning, so that users focus on scanning …
> Post-launch cleanup, better separation for SCP and Semgrep Code

- docs/semgrep-cloud-platform/pricing-and-billing.mdx
**Changes from draft:**
* I noticed an inconsistency in the draft. We say "number of purchased license**s**" then say "purchase an annual license for 50 developers" in the example. This has been corrected to "purchase annual licenses for 50 developers".
* Created a header for the example and made it clear for the right-side TOC
* Replaced "Should the organization exceed the number..." with "If the organization exceeds the number..." for conciseness and clarity.
* Removed "we recommend" because :
* If we use "we" we should state who we are referring to before hand (I can update if we choose to do this, something like "Semgrep Inc recommends...")
* It's not actually a recommendation 😅 - if they plan to go over their plan limits, they will **have** to talk to us. (That being said, the …
> trueup, license reconcilliation

- .github/workflows/algolia-scrape.yml
Doubles the sleep to make sure our docs build when the scraper runs (i.e. race condition "prevention")
> updated timeout

- docs/semgrep-ci/running-semgrep-ci-with-semgrep-cloud-platform.md
Updates the path in the link within "Receiving PR or MR comments" section. There is a redirect for the current path to the one I'm updating to, but it seems not to be working consistently.
My pleasure. 😁
> Update "Alerts and notifications" link

- docs/semgrep-cloud-platform/user-management.md
> member roles can only read

- docs/writing-rules/rule-syntax.md
> `focus-metavariable` can be a list

- docs/kb/rules/using-pattern-not-inside.md
My rule with `pattern-not` doesn't work: using pattern-not-inside
Guidelines on how to understand and use `pattern-not-inside`.
I've run the app locally and verified that the embeds are working as expected.
> [New KB] My rule with pattern-not doesn't work: using pattern-not-inside

- docs/writing-rules/rule-syntax.md
> Remove pattern-where-python - deprecated syntax

- docs/writing-rules/rule-syntax.md
- src/components/reference/_language-extensions-tags.mdx
- Update according to: https://github.com/returntocorp/semgrep-langs/blob/main/lang.json
- Remove Hack as the support level is only develop
> Update supported language extensions table

- docs/kb/rules/run-all-available-rules.md
- run-all-available-rules.md
How to run all available rules within the registry.
This kb talks about the use of `--config=r/all` when wanting to run all available rules within the registry on a repository.
> [NEW KB] How to run all available rules within the registry.

- docs/semgrep-cloud-platform/github-pr-comments.md
This looked like a copy-pasta issue - the note it should refer to the thing that the page focuses on configuring, not something else.
> Remove reference to Slack on PR comment page

- docs/contributing/semgrep-core-contributing.md
Updated the documentation with the correct command for making core install, (just changed make install to make core-install)
> fixing small typo, install -> core-install

- docs/semgrep-code/policies.md
- docs/semgrep-code/rule-board.md
On June 14 we shifted from beta-testing the new Policies (Rule management) to making it the default. This update reflects that in the tips at the top of each relevant page.
[Linear issue](https://linear.app/semgrep/issue/MKT-680/update-rule-board-and-policies-docs-to-reflect-new-policies-as-default)
> Update admonition to reflect Policies as default

- docs/faq.md
- docs/index.md
- docs/playground.md
- docs/semgrep-code/editor.md
- docs/writing-rules/experiments/display-propagated-metavariable.md
- docs/writing-rules/generic-pattern-matching.md
- docs/writing-rules/pattern-syntax.mdx
- docs/writing-rules/rule-ideas.md
- docs/writing-rules/rule-syntax.md
> chore: fix urls to broken snippets

- docs/faq.md
- docs/index.md
- docs/playground.md
- docs/semgrep-code/editor.md
- docs/writing-rules/experiments/display-propagated-metavariable.md
- docs/writing-rules/generic-pattern-matching.md
- docs/writing-rules/pattern-syntax.mdx
- docs/writing-rules/rule-ideas.md
- docs/writing-rules/rule-syntax.md
In https://github.com/returntocorp/semgrep-docs/pull/1082/files many links to our rules have been fixed. @jbergler suggested to change these links to permalinks.
> chore: include permalinks, additional minor formatting and textual edits

- docs/getting-started.md
The steps under "To install and run Semgrep OSS Engine, use one of the following options" previously had a single step that was in a tab set - the installation step for the platform - followed by two steps outside the tab set, to verify and run that were the same for each platform.
However, this doesn't work for Docker - if you're running Semgrep locally via Docker, the invocation is different. With this revision, all steps are in a tab set - which leads to some duplication - but the steps are also all correct. 😄
> Update "Installing and running..." section: provide correct Docker commands

- algolia-config.json
~~- [ ] A subject matter expert (SME) reviews the content~~ Sara is the SME
~~- [ ] This change has no security implications or else you have pinged the security team~~
~~- [ ] Redirects are added if the PR changes page URLs~~
~~- [ ] If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link~~
Yet again I tried to change the settings from the Algolia dashboard and yet again they were overwritten by our algolia config json upon build and so here we are, me, at the crossover of the ["you can't stop me, cuz I can't read"](https://i.kym-cdn.com/entries/icons/original/000/024/196/sign.jpg) meme and Sisyphus rolling a boulder up.
This finalizes the fix and hopefully I will learn my lesson and stick to controlling Algolia from our source of truth.
It …
> update typo tolerance

- docs/writing-rules/rule-syntax.md
This PR just changes the rule syntax to reflect https://github.com/returntocorp/semgrep/pull/8115, which causes numeric capture group metavariables to no longer exist.
Closes PA-2896
> fix: change regex capture group docs

- docs/kb/rules/match-absence.md
One question we get is how to match the absence of a pattern, which is currently not supported natively as at least one positive pattern is required. This KB gives an option using pattern-regex.
> [New KB article] Match the absence of something in a file

- docs/supported-languages.md
The "Known limitations of Semgrep Pro Engine" should not be under Supply Chain. This PR pulls it & its children up one H level so it isn't nested incorrectly. Also made a small grammar fix.
> Small hierarchy & grammar fix to Supported Languages

- docs/kb/semgrep-cloud-platform/sso-attribute-error.md
Addresses [CSE-505](https://linear.app/semgrep/issue/CSE-505/missing-attribute-sso-error-badrequest-saml) (internal link), explains likely reasons for error and links to related docs.
I tested out use of the `MoreHelp` component in the KB here, and have submitted a potential update to that component to link to the Support page so that it isn't just pointing to Community Slack, as those running into SSO errors likely have additional options (https://github.com/returntocorp/semgrep-docs/pull/1108).
> [New KB Article] Resolve SSO attribute error

- docs/writing-rules/private-rules.md
Clarifies the steps necessary to publish a rule as private to the Registry from the Editor.
> Add private publication steps for Semgrep Editor

- docs/kb/semgrep-cloud-platform/inline-pr-comments.md
[CSE-519](https://linear.app/semgrep/issue/CSE-519/why-were-prmr-comments-left-as-summary-comments-instead-of-inline) (internal link).
Explains the two most common reasons why Semgrep comments on a PR or MR might not appear inline.
> [New KB Article] Why did the comments on a PR or MR not appear inline?

- docs/semgrep-supply-chain/overview.md
We get a fair number of questions about this term, and previously it was only defined in the filter descriptions. This PR adds it to the overview page along with the other possibilities.
> Add definition of Undetermined to SSC overview

- docs/contributing/semgrep-core-contributing.md
- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
- docs/troubleshooting/semgrep.md
Addresses [CSE-527](https://linear.app/semgrep/issue/CSE-527/update-scan-troubleshooting) (internal link). 
Move some troubleshooting material to the KB, and move contributor-related content to the Contribution docs.
For now we'll go with the "move & link" approach but we might consider delete & redirect later.
> Scan troubleshooting: Move more content to KB, move some to Contributing

- src/components/reference/_supported-languages-table.mdx
removing dart from experimental, while we fix it's parsing issues
> removing dart from experimental

- docs/getting-started.md
- docs/kb/semgrep-code/run-specific-version.md
This came up when I did a copy-pasta of the Getting Started doc into a KB and @s-santillan pointed out that the sentence sounded a bit strange without a verb for running the command. It turns out Google prefers if you just describe the effect or result of the command so simplifying to that.
> Update installation commands to Google style (describe result/effect of command)

- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
Small addition to the Scan troubleshooting KB article mentioning disabling a rule if it's causing issues.
> Scan Troubleshooting KB: Add note about disabling rules that have been excluded

- docs/kb/rules/ellipsis-metavariables.md
- docs/writing-rules/experiments/aliengrep.md
* Add a guide for using ellipsis metavariables to match multiple word tokens in generic mode (a relatively common question).
* As part of this addition, I checked whether "ellipsis metavariable" is the desired standard, and brought the new/experimental Aliengrep mode document into that fold.
* While I was editing the Aliengrep doc I also did some other light Vale style linting on it. I didn't attempt to change the first-person usages because they were extensive, but I fixed uses of will and other smaller suggestions.
> [New KB Article] Matching multiple tokens with ellipsis metavariables

- src/components/reference/_supported-languages-table.mdx
~~- [ ] A technical writer reviews the content or PR~~ XS size PR, not needed
I set Rust as experimental for intrafile because we have not extensively tested it.
Removed beta from terraform as discussed.
> updated based on pa team

- docs/writing-rules/rule-syntax.md
As of https://github.com/returntocorp/semgrep/pull/8406, we now support `in` and `not in` for strings. This just changes the docs.
> feat(rule syntax): add string in docs

- src/components/code_snippets/_circleci-semgrep-app-standalone.mdx
SAST standalone snippets should not use the `--supply-chain` argument :)
There are some more complex issues with this snippet but I've raised those in a separate internal issue for discussion - this fix at least gets us running the right product.
> CircleCI snippet fix: SAST snippet was running SSC instead

- docs/getting-started.md
@sebasrevuelta This PR adds back some of your tips:
- Added prerequisite and link to install WSL in getting started docs
- Added helpful docker command specific to windows when running semgrep in docker in windows
There are several helpful commands you included (running env vars in docker, specifying target folder) that I haven't figured out yet where to place, namely "running semgrep with a specific target directory or module". I think they should go into a Semgrep Usage tips or Helpful Semgrep Command Combinations guide. I will find a place for them, maybe in Semgrep CLI, as an "Appendix" or "Common use cases for Semgrep CLI". I have opened a [linear ticket here](https://linear.app/semgrep/issue/MKT-713/common-uses-and-workflows-for-semgrep-cli) so that everything you wrote has a place …
> add instructions on running semgrep docker windows

- docs/semgrep-cloud-platform/tags.md
Updated the verbiage to explain how tag setting works via API and settings file. Also changed the docusaurus admonition to type "caution" to better reflect the tone of the message
> Clarify tag setting

- .github/workflows/build-and-deploy.yml
IAM users have static credentials that need periodic rotation (the key for this user is over 200 days old!). Use the IAM role introduced in https://github.com/returntocorp/semgrep-app-terraform/pull/1140 instead to enable the workflow to use temporary creds using OIDC like in most other workflows.
> Use IAM role instead of IAM user

- docs/kb/semgrep-cloud-platform/inline-pr-comments.md
I found my own KB in a search today (lol) and realized it was weird from that perspective that it doesn't link to the docs for enabling comments. 
Logically speaking, for this KB to be useful, you need to already have them enabled, but you might still land on it in other circumstances. 😄
> Add references to enabling comments docs

- docs/semgrep-code/semgrep-pro-engine-examples.md
- docs/semgrep-code/semgrep-pro-engine-intro.md
> `interfile: true` should be under `options`, not `metadata`

- src/components/reference/_supported-languages-table.mdx
https://github.com/returntocorp/semgrep/pull/8704 will add Experimental support for Dart to Semgrep. This PR just updates the documentation.
> chore: add dart to supported languages

- .github/workflows/update-help-command.yml
Instead of committing directly to `main`, which would fail because it's a protected branch, we generate a PR, with a PR branch named based on the latest semgrep release tag, so the branch name is always unique.
> Update `update-help-command.yml` to auto-create a PR

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
> Add language maturity definitions for Pro Engine

- src/components/code_snippets/_azure-semgrep-app-standalone.mdx
- src/components/code_snippets/_bitbucket-semgrep-app-standalone.mdx
- src/components/code_snippets/_buildkite-semgrep-app-standalone.mdx
- src/components/code_snippets/_circleci-semgrep-app-standalone.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone-dash.mdx
- src/components/code_snippets/_gha-semgrep-app-standalone.mdx
- src/components/code_snippets/_glcicd-semgrep-app-standalone-dash.mdx
- src/components/code_snippets/_glcicd-semgrep-app-standalone.mdx
- src/components/code_snippets/_jenkins-semgrep-app-standalone.mdx
At the moment this change won't have any effect in the user-facing docs, since we removed these snippets from the CI configuration reference earlier, but this prepares us for adding them to the KB in the future.
The change is to remove reference to SEMGREP_RULES which is not compatible with `semgrep ci`, and instead execute with the `--code` argument, which was added in [1.40.0](https://github.com/returntocorp/semgrep/releases/tag/v1.40.0).
> Update SAST standalone snippets with --code

- docs/cli-reference.md
This is mostly a nitpick, but the current language might have two interpretations:
1. The `--error` flag needs to be used
2. An `--error` flag is set when issues are detect
This is an attempt to make the language clear that the `--error` flag must be used for Semgrep to exhibit this behaviour.
> Update --error flag description in exit codes section

- docs/kb/semgrep-ci/git-command-errors.md
We get occasional reports of folks who see git commands failing during a Semgrep scan and aren't sure why. The current error suggests a few common fixes, but there are a couple that are a bit more complicated and for now are more suitable for a KB - hence this article.
(It's possible that after the osemgrep port is complete we can improve the errors in Semgrep directly.)
> New KB article: Failed to run a git command during a pull or merge request scan

- docs/semgrep-ci/sample-ci-configs.md
The primary goal here is to clarify that the use of `main` in the new snippet represents main as the default branch, and users should substitute their own default branch if needed.
I also made some wording adjustments and linted the file (which mostly meant replacing BitBucket with Bitbucket in this case).
> Branch clarifications and wording improvements for CircleCI instructions

- .github/workflows/update-help-command.yml
Now that we are running the canary release, it makes more sense to just explicitly use the latest version of semgrep in the docker tag instead of `latest` which will always be 1 version behind.
> Use latest version for docker image instead of `latest`

- docs/writing-rules/pattern-syntax.mdx
to avoid confusion. I tried to avoid too many `==` examples, and for the one I left in, I made sure to build it gradually and explain it better.
> Updated examples and explanation for Typed Metavariables

- sidebars.js
The following issue:
arises when a higher-level category in the sidebar is a link to DocumentA, which is then re-referenced as the first item. Therefore:
```
Document A
└╴ Document A
```
It looks like this in sidebars.js:
To correct this, we should not duplicate DocumentA as the first item. There are some examples of the correct behavior CURRENTLY - try clicking on Ticketing or Notifications in the [semgrep.dev/docs](https://github.com/returntocorp/semgrep-docs/pull/1235) and you'll see that the Next button correctly moves to the next document. 
The other correction is to use a generated index instead of a link to a document as the higher-level category. I applied that fix for the release notes fixes.
> fix all next links not working

- docs/contributing/semgrep-core-contributing.md
Reverts returntocorp/semgrep-docs#1234
While some of the team is internally using 5.0.0 this isn't the official build process yet.
> Revert "Update semgrep-core install instructions"

- docs/supported-languages.md
Probably we used to have this as part of a page but now it's its own page so let's link there
> Link directly to Maven instructions

- src/components/reference/_supported-languages-table.mdx
Moving Rust to GA for cross-function, now that it's a GA language in OSS.
> Moved Rust to GA for cross function

- docs/kb/semgrep-code/collect-cli-logs.md
- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
Some folks have run into small hiccups collecting Semgrep logs because of the separation between stdout (findings) and stderr (scan progress). This doc provides a more in-depth guide, as well as linking to the main scan troubleshooting resource.
> [KB] Add KB for collecting CLI logs (output redirection etc)

- docs/semgrep-ci/sample-ci-configs.md
Adds an info box for folks using Azure to note that (typically older) repos that are controlled with Team Foundations Version Control would have to be migrated to git to work with semgrep ci.
> Azure: Add note about TFVC repos not working with semgrep ci

- docs/extensions/semgrep-intellij.md
> Fix IntelliJ description to say OSS only

- docs/contributing/contributing-rules.md
- docs/ignoring-files-folders-code.md
- docs/semgrep-supply-chain/ignoring-deps.md
- docs/writing-rules/experiments/extract-mode.md
- src/components/reference/_required-rule-fields.mdx
Changed a bunch of anchors and tags that were dangling because the original heading was modified.
In one case, also changed the text of a link (added `ignored`) to the new heading text.
> fix dangling anchors because the heading was modified

- docs/writing-rules/private-rules.md
`semgrep publish --visiblity=unlisted` to `semgrep publish --visibility=unlisted`
> fix semgrep publish typo

- docs/semgrep-code/semgrep-pro-engine-intro.md
changing the [WSL instructions](https://semgrep.dev/docs/semgrep-code/semgrep-pro-engine-intro/#updating-semgrep-pro-engine-in-cli) to remind users they need Python 3.8 installed there as well (and to make it so that the code blocks for Linux and WSL aren't identical which then makes it look like the tabs are broken)
> update WSL admonition

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
- Adds Hack to supported languages list and labels as experimental.
- Adds note about querying Registry for rules if the language is experimental.
> update Support Languages doc with Hack

- docs/pricing-and-billing.mdx
The PR includes some auto-formatting but the core changes are in the screenshot below. The intent is to avoid the reader potentially concluding that one purchases a single item, “Semgrep Team tier,” and then that includes all of Semgrep’s paid products.
> Clarify that team tier things are separate products

- docs/semgrep-code/semgrep-assistant-code.md
In many cases, we provide hints for how to give feedback to Assistant, but it's useful to have it documented also, especially for the cases where we don't give hints (primarily the Assistant-thinks-it's-a-true-positive case).
> Add information about how to provide feedback

- docs/semgrep-cloud-platform/getting-started.md
- src/components/concept/_platform-signin-intro.md
Sometimes folks are confused about whether GitHub Enterprise Cloud is a SaaS thing, so make it explicit. (This might also help the AI know how to answer questions about setup with GHEC.) While doing that we also wanted to make it clear for GitLab - but GitLab has three types of hosting (cloud, SM, and Dedicated) and I believe only cloud/.com will work, so we adjusted a bit further.
> Be explicit about what constitutes GitHub / SaaS

- docs/supported-languages.md
Yo @andy-r2c! Can you confirm `pubspec.lock` and if we have license detection for Dart? :pray:
> add dart support in SSC

- docs/release-notes/october-2023.md
- docs/release-notes/september-2023.md
I wrote some corrections to our existing release notes:
1. Oct 2023 - Added Semgrep Assistant onboarding - we never explained which part of the onboarding flow, so I clarified that it's in the [Getting started guide; the user still has to set up other parts](https://www.notion.so/semgrep/Existing-Semgrep-Assistant-Signup-Steps-5b8d39d8dfea4b5193ad21224d7c9fdf).
2. Based on discussions last week, the personal GitHub to Semgrep org auto connection was [changed](https://semgrepinc.slack.com/archives/D064BEUCFFF/p1704305365388649) for the new Onboarding flow, and for posterity I am noting down this behavior change.
3. Lastly, we say "Add your repositories to Semgrep" but the implied 1-click auto-setup behavior is [exclusive to GHA](https://semgrepinc.slack.com/archives/C02PV1VVAUR/p17044740045 …
> corrections to older messages

- docs/supported-languages.md
Feedback:
> ...language support graph for SCA is confusing. At first glance it feels like we are saying Kotlin has reachability support because the :x: is only for License Detection and there is no :x: for Time Period of Reachability Rule Coverage.
Agreed, it erroneously says "Since May 2022" for all package managers, including those which don't have any reachability rules. Reachability rules for these package managers should be n/a.
> the :x: feels like a very loud "no" where a blank communicates the same, but leaves room for "soon" 
Also agreed, and considering that the language table uses `--`, I went with those for consistency.
> corrected table based on feedback

- docs/kb/rules/match-commments.md
Matching comments with generic mode - a nice little feature that we will now advertise a bit better. :)
> [KB] Match comments with generic mode

- docs/semgrep-code/semgrep-assistant-code.md
Linked the Findings page to Assistant so users can find their results; made minor edits to the page.
> Assistant docs: add link to Findings page; minor edits

- docs/semgrep-code/semgrep-assistant-code.md
Clarify that Assistant doesn't supply autofixes in Slack.
> Add clarity on what Semgrep Assistant does in PR/MR vs Slack

- docs/kb/semgrep-ci/github-upload-findings-in-security-dashboard.md
The previous version of this doc indicated that it wasn't possible to run this job in private repositories. This update clarifies that it is possible if the permissions are set appropriately.
> Explain permissions required for private repositories when using GHAS

- docs/semgrep-ci/ci-environment-variables.md
We'd gotten a bit out of sync on some of these variables, in terms of what they actually do to Semgrep/in SCP. These changes should get us back in line.
> Update branch, commit, and timeout env vars with more accurate information

- docs/writing-rules/generic-pattern-matching.md
The intro on this page suggested generic mode is mostly for unsupported languages or structured data, but it can also be used in other cases where parsing is more challenging, such as mixed content.
> Add note about mixed content

- docs/supported-languages.md
For some reason I thought this info already existed, but basically we should be clear about what the presence of a manifest file does (determine transitivity).
> Clarify why we parse manifest files

- docs/contributing/semgrep-core-contributing.md
The command to install `semgrep core` has been removed since August 2023 (https://github.com/semgrep/semgrep/pull/8512), but the doc wasn't updated. The equivalent command to use is `make copy-core-for-cli`.
> corrected the command to install semgrep-core

- docs/cli-reference-oss.md
- docs/ignore-oss.md
- docs/prerequisites-oss.md
- docs/supported-languages-oss.md
- sidebars.js
See:
- https://linear.app/semgrep/issue/MKT-818/after-new-sidebars-clean-up
- https://semgrepinc.slack.com/archives/C02JT6YA5S7/p1708625378388649
I feel as though the correct answer here is to use partial mdx files and import them, so that there is a single source of truth that is then funneled / cascaded to the doc files but at the same time I feel we're hitting a level of complexity on keeping the docs readable and maintainable. This is, for now, a "quick fix".
> workaround for docs to sidebar association issues

- docs/writing-rules/private-rules.md
I'm not sure why the config on this job was invoking Docker explicitly; it might just be older syntax. This config is simpler and better matches our current sample CI config for regular Semgrep runs.
> Provide simplified `semgrep publish` GitHub Actions job

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
Promotes C and C++ to GA, and adds new community-supported definitions
> Promote C and C++ to GA

- docs/writing-rules/private-rules.md
Adds a basic GitLab workflow file allowing publishing of private semgrep rules from GitLab.
> Add GitLab workflow example for semgrep publish

- docs/cli-reference-oss.md
- docs/cli-reference.md
Helpful tip, even for us internal folks.
WRT to duplication, I am avoiding componentizing our repeating sections until our migration is done. (I am crying inside.)
> update with tip on viewing exit code

- .gitignore
- copy-vs-code-readme-md
- docs/extensions/semgrep-vs-code-helmet.md
- docs/extensions/semgrep-vs-code.md
- run-build-scripts
I removed the integration with https://github.com/semgrep/semgrep-vscode README and made minor edits to the text. The original format made sense for a README but didn't quite for docs. However, there's no substantive changes to the content.
> Decouple VS Code extension docs from its source repo + update text

- docs/writing-rules/experiments/extract-mode.md
In line with https://github.com/semgrep/semgrep/pull/9891
> deprecate extract mode

- docs/ignoring-files-folders-code.md
I think there's a fine line between ignoring code and ignoring findings, but it would still be helpful to link from the ignore page to the triage page so people know where to find the information they want.
> link from Ignoring files, folders, and code to Triage and remediate Semgrep Code findings in Semgrep Cloud Platform

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
- Removes lots of trailing whitespace ... probably from copypasta
- Renders the experimental langs as a list.
-
> render the experimental langs as list

- docs/writing-rules/rule-syntax.md
- src/components/reference/_required-rule-fields.mdx
We've [updated the regex engine in 1.68.0 from PCRE to PCRE2](https://github.com/semgrep/semgrep/pull/9919). There are some minor differences, so some links need to be updated.
> Update for 1.68.0 regex engine change

- docs/semgrep-ci/ci-environment-variables.md
This updates with our new recommendation for how to use each environment and provides example guidance for using SEMGREP_REPO_DISPLAY_NAME to scan a monorepo as separate projects.
> Update docs for SEMGREP_REPO_NAME and SEMGREP_REPO_DISPLAY_NAME

- docs/kb/semgrep-supply-chain/ssc-lockfiles-circleci.md
The title wasn't coming through, it was only showing the filename. It may not be necessary to both specify the title and change to an h1, but I wanted to be safe.
> Give CircleCI lockfile gen article a proper title

- docs/kb/semgrep-ci/git-command-errors.md
Found another failure mode recently, adding it to the doc. This seemed like the best fit place for it since it's not a really common concern.
> [KB]: Git command errors: add note about `git diff --merge-base`

- src/components/code_snippets/_bitbucket-semgrep-app-sast.mdx
- src/components/code_snippets/_bitbucket-semgrep-app-ssc.mdx
- src/components/code_snippets/_bitbucket-semgrep-app-standalone.mdx
- src/components/code_snippets/_bitbucket-semgrep-oss-sast.mdx
When I was pulling the new configs from these docs (#1491) into the app I wanted to see if we could just list the image once, replacing the Atlassian default, and it worked fine, so I'm back-propagating that change into the docs again. 😂 
I know two of the three app snippets aren't in use, so the update on those is just consistency for the future.
> Pull one last change into BB configs, expand changes to OSS

- docs/kb/semgrep-ci/scan-monorepo-in-parts.md
- docs/semgrep-ci/ci-environment-variables.md
Moved the info on using display name to the relevant KB. Decided not to re-use the GitHub Actions example because it used matrices and that's a bit too advanced/confusing to use as a simple example. I think the KB does a good job of explaining how to use the new env var now. Also added a minimum version for the new env var in the variables reference page.
> Move monorepo scanning to KB and update verbiage

- docs/semgrep-ci/network-broker.md
Corrected invalid ipv6 address by replacing it with a variable to keep consistent with the rest of the doc.
> Fix invalid ipv6 address in network-broker.md

- netlify.toml
> Add netlify.toml file so docs serves the Docusaurus 404 page instead of Netlify’s 404 page

- docs/semgrep-supply-chain/sbom.md
Currently, SBOM vulns always come from the default branch and dependency lists from the latest full scan - so those need to match.
> SBOM limitation: latest full scan on default branch

- docs/supported-languages.md
Rust with `Cargo.lock` and Kotlin with `gradle.lockfile` do not support determining whether or not a dependency is transitive, all dependencies will have `Unknown` transitivity. I added this as a footnote.
> add footnote to SSC support languages about transitivity

- docs/semgrep-assistant/overview.md
The paragraph I edited is the description for Assistant Autofix; it doesn't need to link elsewhere.
> remove link to autofix

- docs/writing-rules/private-rules.md
The examples were written as if you would definitely put rules in a subdirectory, but that's not always the case. This update makes the assumption explicit and provides an alternative for the root.
> Explain the directory setting in the `semgrep publish` examples

- docs/semgrep-appsec-platform/dashboard.md
- sidebars.js
- Moves SBOM out of Reporting and into SCA (Supply Chain) in the sidebar. 
- Adds a link on the Dashboard reports page to SBOM doc.
> update SBOM sidebar location

- docs/semgrep-supply-chain/dependency-search.md
For the Dependencies page, we don't actually show dependencies unless they were found off a full scan. This will add an extra note to tell users of the above circumstance.
> Add a note for Dependency Search that only reflects 

- docs/semgrep-secrets/getting-started.md
We'll have more on this in future, but in the meantime, this should help with some confusion we've seen about Secrets with `.semgrepignore`.
> Quick interim note on Secrets ignores

- src/components/reference/_diff-aware-scanning.mdx
Removed a bit of extra whitespace:
> fix formatting in diff-aware scan snippet

- docs/deployment/core-deployment.md
Mostly this just fixes some broken links that didn't have the proper docs path. I also made a few other tiny adjustments (Secrets not officially beta any longer, etc)
> Fix broken links (missing docs path)

- docs/getting-started/cli.md
The Local CLI scans page now links to the OSS quickstart and adds a mention for users who do not have a Semgrep acocunt.
> link to OSS quickstart

- docs/semgrep-supply-chain/getting-started.md
We updated the name of the blocking toggle since it also causes full scans to exit with code 1. I changed the name and lightly modified the verbiage - since we still generally focus on PR/MRs for blocking, I didn't remove that aspect of the content.
> Reflect change of toggle name for SCA blocking

- docs/semgrep-ci/ci-environment-variables.md
I always spell this wrong too, so I'm sensitive to seeing it lol
> Typo fix in CI environment variables page

- docs/kb/semgrep-ci/trigger-diff-scans-env-var.md
This information exists in the docs already, but I pulled it into a single KB article for easy reference.
> add doc on triggering diff scans with env var

- docs/semgrep-code/editor.md
- docs/semgrep-code/overview.md
The term "fork" which the editor uses was not in the section title, and so this section wasn't showing up when searching for "fork rule". Hopefully this will help without being too specific/not clear to new users.
> Including fork in "new rule based on existing rule" section title

- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
- docs/semgrep-code/policies.md
- docs/semgrep-supply-chain/getting-started.md
This is a follow-up to work done in https://github.com/semgrep/semgrep-docs/pull/1589 and is for [this Linear ticket](https://linear.app/semgrep/issue/TEC-64/clarify-blocking-as-it-relates-to-prmr-scans-and-full-scans).
One thing that always gives me pause is that "blocking" isn't strictly "blocking" -- it's Semgrep failing with exit code 1 and then the user has to handle that exit. So, I added that note wherever I thought would be helpful. I also added mentions that blocking works for both full and diff-aware scans, while retaining the PR/MR blocking language that we currently have. Let me know if this is actually muddying the waters and I can revisit how we explain this (do we need a KB-esque guide explaining blocking with all the definitions, including diff-aware vs full scans?)
> clarify how blocking works

- docs/semgrep-assistant/overview.md
Updating the LOC sent to Assistant from 10 to 30 as requested by Jack.
> Update LOC sent to Assistant.

- docs/kb/semgrep-secrets/per-product-ignore-not-working.md
There are other reasons Semgrep might not have ignores files or folders in a Secrets scan, so let's specify exactly which ones are relevant for this guidance.
> Make title of Secrets Path ignores KB more specific

- src/components/reference/_triage-states.mdx
A finding changing to a removed status is not something a user can do directly, it just happens, so we shouldn't really use the active voice here.
> No active voice for removed, since it's not a user action

- docs/index.md
> make quickstart the next link on the homepage

- docs/writing-rules/pattern-syntax.mdx
This confused both me and a customer (who tried to just use `$ARGS` as we would anywhere else). [Playground test](https://semgrep.dev/playground/r/gxU3RYR/relsqui.ellipsis-metavariable-message) to verify I'm right about how it works:
> Show how to reference ellipsis metavariables

- docs/semgrep-appsec-platform/jira.md
We had one word-sub issue in this doc and also were missing details about what happens if you have required fields of types we don't support.
> Clarify field types support / limitations

- docs/semgrep-ci/network-broker.md
And prefer organization to deployment based on UI labeling, but note that it's also called deployment ID.
> Network Broker: Add detail on where to find the org ID

- docs/deployment/connect-scm.md
We removed the PAT connection option for GHE as the app is the recommended connection method.
> Remove PAT option for GHE, no longer available

- docs/semgrep-code/glossary.md
The CS AI (and some newer folks) were unclear that "ruleset" is a specific item, so at least define it in the glossary as a start.
> Add ruleset as a glossary term

- docs/writing-rules/experiments/pattern-syntax.md
adds `as-metavariable` info to experimental rules writing page.
> add notes on using as-metavariable

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
- docs/kb/semgrep-supply-chain/why-no-findings.md
- docs/semgrep-supply-chain/getting-started.md
- docs/supported-languages.md
Our docs didn't consistently mention / explain that you can literally only use the supported lockfile names - this change attempts to make that clear in multiple places.
> Be more clear that SSC scans must use the supported lockfile names

- docs/extensions/overview.md
This is rad, but sadly it hasn't been updated in three years and was archived by the owner a couple of months ago.
> Remove vim extension link

- docs/semgrep-appsec-platform/slack.md
Correcting the hyperlink under "Check your Filters" Section from https://semgrep.dev/docs/semgrep-appsec-platform/slack-notifications#changing-slack-notification-settings to https://semgrep.dev/docs/semgrep-appsec-platform/slack-notifications#change-slack-notification-settings.
> Update the slack notifications hyperlink to correctly redirect

- docs/semgrep-supply-chain/dependency-search.md
There's a KB about not seeing SSC findings, so refer folks to that if they don't see any dependencies also. I made a small wording change because "off of" seemed weird to me, but maybe "in" is better?
> Add link to helpful KB, clarify language a bit

- docs/semgrep-code/policies.md
Some wording clarification and behavior clarification around adding projects/repos to a policy, mainly to make it clear that it's primarily a manual process, but there was also some terminology that seemed odd to me, though I might be missing context on it.
> Currently multiple policies requires manual assignment w/a bit of search help

- src/components/code_snippets/_gha-semgrep-app-sast.mdx
Changing the sample GHA workflow to better match the workflow used in semgrep.dev, as scanning on every push to main is unnecessary.
See slack convo:
https://semgrepinc.slack.com/archives/C02PV1VVAUR/p1715284784859239
> Update GHA sample workflow to only do full scan when workflow file changes or on a cron schedule

- docs/semgrep-assistant/getting-started.md
> Fix order of Assistant Memories screenshots

- docs/cli-reference.md
Using tabs for the `scan` vs `ci` output makes a lot more sense to me and looks pretty clear. I know there was discussion around why we didn't use tabs to begin with, but I'm hoping to spark that up again here now that we can also see what it looks like with tabs vs one long scrolling page.
Additionally, CTRL/CMD+F on the webpage is better when using tabs, so you don't get duplicate results.
> Update CLI reference to use tabs

- docs/semgrep-secrets/historical-scanning.md
The provided `semgrep scan` command doesn't work anymore/right now. We might be able to restore it, but the ci + dry-run option seems most consistent for now.
And there was some weird wording.
TW reviewer: I'm uncertain how we should approach "historical scanning" vs "historical scans" in this article. The toggle in the app is currently called "Historical scanning" (though we could change that, in theory), but usage in the doc was mixed between "scanning" and "scans". I understand we're generally moving toward plain verbs rather than gerunds, but sometimes the use of plain verbs causes weird sentence structure, particularly in the sentence about diff-aware and historical scans. I welcome your feedback and suggestions to find the best option here.
> Wording and command fix for historical secrets

- docs/semgrep-ci/network-broker.md
The list numbering + all the snippets and screenshots was making this doc confusing. I propose we replace the outer list with H3 sections, each of which has a sub-list if necessary, to make navigation/linking/references easier.
> Restructure network broker doc with sections and shorter lists

- docs/writing-rules/pattern-syntax.mdx
This [came up in the community slack](https://semgrep.slack.com/archives/CK86BJ5DW/p1722930455768219) and it took a little digging to figure out [why my first attempt wasn't working](https://github.com/semgrep/semgrep/issues/6299#issuecomment-1287082436).
It might also be worth clarifying why the pattern here has two sets of quotes (the outer one gets stripped when the yaml file is interpreted -- it's only really necessary because the literal metavariable is the entire pattern) but I wasn't sure how to do that succinctly or if this is where it belonged, so I left it for a future update.
> Add a caution about using literal metavariables with metavariable-pattern

- docs/kb/semgrep-code/semgrep-scan-troubleshooting.md
Correcting the hyperlink under "Scan failures with analysis errors" section (sub-bullet of #1 point) from https://semgrep.dev/docs/semgrep-code/policies#disabling-rules to https://semgrep.dev/docs/semgrep-code/policies#disable-rules.
> Update a hyperlink to correctly redirect

- docs/semgrep-ci/sample-ci-configs.md
This came from a followup with the same user who suggested the original tip -- it turned out both were necessary in their case. I don't want to make a specific suggestion here because it would require tracking Bitbucket's infrastructure settings, so instead I'm pointing out both tuning tools.
> Point out `-j` in the Bitbucket memory tip

- docs/semgrep-code/editor.md
Another one that came up in customer chat, clarifying how forked rules relate to the originals (not at all) and what you need to do next to use one after creating one.
> Add next step hints after forking a rule

- docs/writing-rules/rule-syntax.md
This addresses the documentation side of [#8577](https://github.com/semgrep/semgrep/issues/8577) (but not the question of how the regex parser should behave, only accurately representing how it does).
> Update metavariable-regex docs about anchoring

- docs/semgrep-appsec-platform/jira.md
We made a behavior change and this is section no longer accurate. Users can freely assign component mappings and can expect ticket creation in non-default projects to work if a component with the same name is available in that project.
> Update Jira component disclaimer

- docs/semgrep-supply-chain/getting-started.md
This being an HTML link instead of a markdown link meant that `/docs` wasn't automatically prepended to the link provided.
[Working preview](https://deploy-preview-1704--semgrep-docs-prod.netlify.app/docs/semgrep-supply-chain/getting-started#event-triggered-scans)
> fix broken link, attempt 2

- docs/writing-rules/rule-syntax.md
See: https://semgrep.dev/docs/writing-rules/pattern-syntax#string-matching
> Remove cross-reference to deprecated string matching

- docs/semgrep-code/editor.md
This doc had gotten a bit out of date with some of the current defaults of the editor. It also needed a few minor fixes. I added a short section on organizing rules because we often get questions about creating folders for custom rules and it isn't possible.
I changed one header tag, but found no instances of that link to update.
I don't think this change has security implications. I am updating the doc to describe a newer behavior that is more secure by default.
> Semgrep Editor: update defaults/tiering, discuss rule organization

- docs/semgrep-code/semgrep-pro-engine-examples.md
- sidebars.js
- Adds back Semgrep Pro Engine examples to the sidebars.
- Simplifies explanation of proprietary semgrep (**both** cross-file and cross-function taint analysis).
- Removes excessive callouts.
> remove semgrep pro engine, replace with semgrep

- docs/getting-started/cli.md
- src/components/procedure/_login-activate.mdx
The quickstart explicitly tells users to sign in, so I opted not to add any admonitions; let me know if you think we should have them anyway
> add warning about needing to be signed in to use semgrep ci

- src/theme/DocItem/Content/index.tsx
Some docs had the tags (eyebrow) appear after the title. This is the fix.
> fix positioning of eyebrow tags

- docs/supported-languages.md
**We now support license detection for pnpm and yarn 2 & 3**
Here is a preview:
Additionally, I am aware we are working on backfilling till may 2017 so just let us know when to update the date, as well.
> update pnpm yarn

- docs/extensions/overview.md
Asking users to clone all of semgrep to use pre-commit was a lot, so we made a separate pre-commit repo that is now automatically updated on each Semgrep release.
> Refer to new pre-commit repo

- docs/semgrep-assistant/overview.md
Assistant uses different amount of code for different tasks. This is also subject to change as we make progress. 
Proposing to be less specific so that we can have flexibility.
> Reduce specificity of lines of code Assistat needs

- src/components/reference/_supported-languages-table.mdx
there was a stray character in the supported languages table.
> remove extra character

- docs/deployment/sso.md
Our app doesn't support Microsoft Entra with OpenID; add a warning and redirect users to setting up with SAML.
Authentication is security-related, but this aspect of it is logistical (which type of SSO to use) so I've checked the box below that the change has no security implications.
> No support for Entra with OpenID currently

- docs/semgrep-appsec-platform/webhooks.md
Now that we use plain verbs, we need to do that in links too.
(I didn't change any, but someone did. :) )
> Fix anchor link de-verbing

- docs/deployment/managed-scanning.md
Some folks are not converting fully to Managed Scans for every repo they migrate, so this explains that you can retain the workflow file if it's appropriate.
> Be clear that removing the workflow file is typical but optional

- docs/semgrep-ci/network-broker.md
When the formatting for these URLs was redone, they were also all set to the same path value after the base URL, but that's not right - the API path for each SCM is different and needs to be correct or the customer's config won't work.
> Correct API URLs for GH/GL

- src/components/reference/_cli-help-ci-output.md
- src/components/reference/_cli-help-scan-output.md
> correct misspelling of 'default'

- docs/usage-and-billing.mdx
Updates to remove Semgrep Pro from the doc and position Semgrep AppSec Platform (Semgrep) as the totality of our paid offering. Also simplifies wording around logged-in scans counting towards contributor count
> follow up clean up

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
- src/css/custom.scss
Milan pointed out that on long tables (multiple rowspans) the cell may appear empty at the top of the fold or a typical 900px macbook viewport, because the valign is at the middle of the rowspan, which is not (yet) visible.
Fix: valign to top.
> update valign to top

- docs/index.md
- docusaurus.config.js
- src/css/custom.scss
Was not easy to resize previews in this GH PR comment, so please check this doc: [Screenshot of fixes.](https://docs.google.com/document/d/1fHO9ukjByAprkES2zbWjb37Tqha8LthMDkTckp48xDs/edit?tab=t.0)
Fixes
- Header - controversial - remove "Semgrep" text (look at screenshot, Semgrep goes under the search bar on 380px)
- For some reason, docusaurus sets this in the config file, where it seems I can't swap out a longer asset for a shorter one based on breakpoints a la `content` as I would in CSS.
- Reduce padding between breadcrumbs and logo in article (see arrow)
- Fix Semgrep logo and Semgrep docs by changing arrangement from horizontal to vertical (see arrow)
- Made text a little smaller, in line with reduced size on phones (this still respects if the user overrides the setting)
- Fixed …
> Readability improvements in mobile

- docs/semgrep-ci/network-broker.md
[Preview of new tabs for SCM config
](https://deploy-preview-1829--semgrep-docs-prod.netlify.app/docs/semgrep-ci/network-broker#update-the-config-with-your-scm-information)
[Preview of new info re: `allowCodeAccess`
](https://deploy-preview-1829--semgrep-docs-prod.netlify.app/docs/semgrep-ci/network-broker#use-semgrep-network-broker-with-managed-scans)
> add tabs and add allowCodeAccess info for SMS

- docs/troubleshooting/semgrep-app.md
Folks sometimes see this message if a scan is long as well so this clarifies that the scan results will still be accepted if the scan is running.
I removed the last troubleshooting bullet and related statement since they are incorrect. Modifying `--timeout` only changes how much time Semgrep spends on a rule/file combo. There is no global timeout for Semgrep, only whatever the running system enforces.
For this PR:
requires changes to `semgrep-app` as well. I considered not changing the header but now that we link from the Scans page too it's really wrong.
I think the best bet here will be to put the PR in to semgrep-app, and once it's merged and I know it's going to go out, merge this around the same time. So I want to get approvals lined up before this is actually done, but I have a …
> Update description and troubleshooting for longer scans

- docs/semgrep-code/findings.md
- docs/semgrep-secrets/getting-started.md
The git hash and line of code link in findings details go to different places. This adds a couple of bullet points about what those places are.
AFAIK the same thing is true for Secrets and SSC but I didn't see a parallel page for either of them where we could make this same change.
> Clarify difference between code links

- docs/semgrep-ci/configuring-blocking-and-errors-in-ci.md
This paragraph was confusing because it suggested that the default result for an internal error would be 2 when it's actually 0. The content below is correct so refer to that instead.
> Clarify default behavior vs options for handling exit codes

- docs/semgrep-code/triage-remediation.md
We don't do support through semgrep.dev, that goes through semgrep.com
~- [ ] A subject matter expert (SME) reviews the content~ xs change and I am an SME
> Correct support link

- docs/kb/integrations/pagination.md
> update API example on pagination KB

- docs/semgrep-ci/sample-ci-configs.md
We test our sample config on Azure hosted runners; this adds a note to let folks using self-hosted runners know they might need to adjust. It's planned to be followed by adding KBs with examples of how this could work for the default *nix self-hosted image.
~- [ ] A subject matter expert (SME) reviews the content~ xs PR
> Add caveat about hosted runners for Azure

- docs/semgrep-secrets/view-triage.md
The Secrets triage page hadn't been updated to reflect the new triage states and ticketing integration changes. It also didn't mention that secrets findings may end up becoming invalid rather than being fully fixed. And we had a secret ox hiding in the doc. 🐂 😆
> Update secrets triage to fix some errors/old info

- docs/extensions/overview.md
- docs/kb/integrations/customize-semgrep-precommit.md
I've fielded a few questions about ways to modify Semgrep's behavior in pre-commit, so this guide offers both a couple of specific examples and some more general notes about how the existing hooks work that I hope will help folks self-serve more generally.
I added a link to the related doc, and Vale was bugging me, so I also cleaned it up a bit.
> [KB] Customize Semgrep in pre-commit

- docs/cheat-sheets/rails-xss.mdx
- docs/extensions/overview.md
- docs/ignoring-files-folders-code.md
- docs/semgrepignore-v2-reference.md
- sidebars.js
This a reference for the new (v2) Semgrepignore mechanism. I wrote it such that it's complete and also covers the legacy v1. This is currently available with `--experimental` which includes other things than file targeting but we'll soon provide a flag to use just this new feature (we'll also make some users use it by default). For now, having this document out there is useful for CSEs and other stakeholders who need to manage a smooth transition to v2.
Preview:
* https://deploy-preview-1861--semgrep-docs-prod.netlify.app/docs/ignoring-files-folders-code#define-ignored-files-and-folders-in-semgrepignore
* https://deploy-preview-1861--semgrep-docs-prod.netlify.app/docs/semgrepignore-v2-reference
> Add a reference for Semgrepignore v2 (and v1 at the same time)

- docs/kb/semgrep-ci/scan-compressed-files-artifacts.md
- docs/kb/semgrep-code/InvalidHeaderValue.md
People ask a lot if Semgrep can scan compressed files/other binaries, let's give them an answer.
I noticed that I wanted to add a "Scans" tag here and there was already "Scanning" on the other file I modified. Since we prefer simple verbs (and presumably simple nouns, if tags are nouns ;), I aligned both to "Scans". I removed "Secrets" since it could be confused with Semgrep Secrets and that's not what the other KB is about.
> [KB] Does Semgrep scan compressed files?

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
- docs/semgrep-supply-chain/overview.md
- docs/semgrep-supply-chain/triage-remediation.md
- docs/supported-languages.md
A set of updates mostly focused on Python lockfile info, but with a few other bits of cleanup - statuses no longer gated by Jira beta, remove otherwise unused tags.
Note: SME approval will be important for this PR.
> Cleanup mostly around requirements.txt changes/usage

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
GitHub is [deprecating v3 of their artifact workflows](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/), so we should proactively update.
> Update artifact workflow versions

- docs/kb/rules/understand-severities.md
Probably in an ideal world we'd rename this, but for now I'm just going to go with adding this info. The info came from the Code team and is only lightly paraphrased :)
> Add confidence since people ask about this too

- docs/semgrep-supply-chain/dependency-search.md
> Add info on dependency paths poetry support

- docs/extensions/overview.md
The asdf-semgrep plugin has been non-functional since March 2023 due to a change in release artifacts introduced in Semgrep v1.16.0.
See issue here: https://github.com/brentjanderson/asdf-semgrep/issues/1
This was noticed by a Semgrep customer that uses asdf. They requested that we remove reference to non-functioning extensions.
> Remove reference to the asdf-semgrep plugin

- docs/semgrep-supply-chain/sbom.md
- src/components/reference/_admonition-sot-cves.md
Tiny PR. I checked our **Advisories** tab and we don't show the source of the CVE (yet) so I just listed electron release notes as a source.
> add electron as a source (xs sized PR)

- docs/supported-languages.md
When I went back to check the announcement and code for this change, it actually accounts for any requirements file of any of the formats ending in either `.txt` or `.pip`, which wasn't quite what we wrote originally (or what I wrote when I updated it recently 🤦🏻‍♀️ ).
> Match requirements file patterns to actual functionality

- docs/kb/semgrep-supply-chain/ssc-python-lockfiles.md
This KB is about generating lockfiles, defined as files that list specific pinned dependency versions. These are the only files we currently support for Python with SSC.
> Fix incorrect references to manifest files

- docs/contributing/adding-a-language.md
- docs/contributing/updating-a-grammar.md
The contributing docs that explain how to add and update a programming language use a placeholder `X` to refer to the name of the language. This commit updates the docs to use `$PL` as the placeholder instead.
Using `$PL` makes it easier to copy and run the code samples in the documentation, and `$PL` is more descriptive than simply `$X`.
> Replace X placeholder with environment variable

- docs/extensions/semgrep-intellij.md
- docs/extensions/semgrep-vs-code.md
- src/components/reference/_ide-list.md
- See linear and Slack for context.
- Converted to table because listing the links inline might cause the user to skip them (which was the issue)
- Shortened titles of extension docs
> Make links clearer in extensions overview (quick win)

- docs/supported-languages.md
Yarn is the only package manager we currently mention multiple versions for, and we only say 1-3, even though we also support yarn v4. This change makes it clear we support all versions of npm, yarn and pnpm. I think it would also be reasonable to just drop mention of versions from all three, to keep consistent with the rest of the able.
> fix: clarify we support all versions of npm, yarn and pnpm for SSC

- docs/index.md
- docs/release-notes/january-2025.md
- docs/release-notes/latest.md
> update wording re: dependency paths

- docs/deployment/customize-ci-jobs.md
It wasn't super clear from the wording that the rule timeout is per file and that it doesn't set a timeout on the whole job at any point, so I tried to clarify that. Open to further adjustments!
> Clarify how rule timeout works

- docs/contributing/semgrep-core-contributing.md
In https://github.com/semgrep/semgrep-proprietary/pull/2932, I am updating nearly everything to OCaml 5. For now, we can still build on OCaml 4, but on macOS we need to use OCaml 5 because there are some specific things that we had to change regarding static linking. At this point, the path of least resistance is for contributors to use OCaml 5.
I also slightly simplified the instructions here, and modified them to create an opam switch named `semgrep` (it's a good idea to keep a separate switch for each project).
> Update contributing instructions for OCaml 5

- docs/deployment/managed-scanning/azure.md
Updating the ADO PAT token scopes for SMS:
- add `Code: Status` scope since it is required for creating commit status and PR status
- remove `Service Hooks` scopes since they are not available in the scopes list when configuring PAT in ADO
Regarding scopes required for managing webhook subscriptions in ADO, I wasn't able to find a definitive answer from ADO docs (more details on it in FS-2005). But when I tested with a PAT that had the scopes in this PR, creating a webhook subscription worked.
> Update ADO PAT token scopes required for SMS

- docs/semgrep-appsec-platform/wiz.md
- docusaurus.config.js
- sidebars.js
Verified that https://deploy-preview-2003--semgrep-docs-prod.netlify.app/docs/kb/integrations/wiz redirects properly to https://deploy-preview-2003--semgrep-docs-prod.netlify.app/docs/semgrep-appsec-platform/wiz
> move Wiz doc from KB to main docs

- docs/deployment/connect-scm.md
- Fixes TEC-294. Additionally adds a callout that says SSO must have been set up first (because "usually" SSO is set up after) before performing the connection.
- Updates "integration" with "connection" because "connect" is used in the Semgrep AppSec Platform UI.
- **I am not sure about using double nested tabs**, feedback welcome.
> Sara/tec 294 docs add GitHub app installation and connection workflow

- docs/contributing/contributing-rules.md
No new content, just putting some nudges towards the updating documentation higher on the page and making it more clear that the platform process can't be used to revise already-published rules.
:heart:
- ~~This change has no security implications or else you have pinged the security team~~
- ~~Redirects are added if the PR changes page URLs~~
- ~~If you have changed any header tag links (doc/#this-kind-of-anchor), update all instances of that link~~
> Clarify that contributing through the platform is for new rules

- docs/semgrep-supply-chain/setup-maven.md
It looks like we missed one instance of `ubuntu-20.04` in our CI examples. This fixes that.
> replace 20.04 in maven sca example gha workflow

- docs/release-notes/january-2025.md
- docs/semgrepignore-v2-reference.md
- src/components/reference/_cli-help-ci-output.md
- src/components/reference/_cli-help-scan-output.md
This a global search-and-replace for "scanning root" that becomes "scan root". I'm the one who originally started using the term "scanning root" but I realized "scan root" makes more sense after noticing a user using the term.
> Replace 'scanning root' with 'scan root' because it sounds better

- docs/deployment/connect-scm.md
1. Simplified the links into 1, since previously both links were the same doc in different versions of BBDC.
2. Clarified that we need `PROJECT_ADMIN` permissions.
3. Refined steps a bit further based on Slack discussion and JK's doc. Details on Slack. You will notice the instructions in the docs instead point the user to the BB docs to generate the HTTP_ACCESS token. Why? Because BB can change its steps any time and the docs are for all users current and future. For specific cases, listing the steps in 1 place is better for the user/demo. But for general cases, where we can't guess if BB suddenly changes its UI, we leverage their content to ensure correctness.
Preview: https://deploy-preview-2028--semgrep-docs-prod.netlify.app/docs/deployment/connect-scm#connect-to-on-premise-orgs-and-pro …
> [xs] Add project_admin permissions

- docs/writing-rules/rule-syntax.md
A user was confused by the original phrasing.
Also, I changed the `**/*.jinja2` example into one that makes more sense (since `**/*.jinja2` is equivalent to `*.jinja2`).
> Clarify "Excluding a rule in paths"

- docs/semgrep-appsec-platform/email.md
- docs/semgrep-appsec-platform/jira.md
- docs/semgrep-appsec-platform/notifications.md
- docs/semgrep-appsec-platform/slack.md
- docs/semgrep-appsec-platform/webhooks.md
- src/components/procedure/_integrate-slack.mdx
At some point name of add integration button was changed from "Add Integration" to just "Add". This PR updates all instructions to reflect that, except release notes which are historical artifacts.
> Update name of button to add integration

- docs/semgrep-code/triage-remediation.md
GHE is always allowed, GH is only allowed if private. Double-checked in the code to confirm, but will also request SME review.
> PR comment: GH logic was backwards

- docs/ignoring-files-folders-code.md
Adjusted some wording to accommodate global ignores.
> Account for global ignores in two places

- docusaurus.config.js
Redirects for all docs created prior to the first week of May 2024 under `/kb/semgrep-cloud-platform` to `/kb/semgrep-appsec-platform`
> add redirects

- docs/contributing/philosophy.md
We usually link to the site but the site is for AppSec Platform and this page is specifically for CE, so don't see the harm in updating.
> Update link to specify repo over website

- docs/deployment/managed-scanning/gitlab.md
- docs/getting-started/quickstart-sms.md
- src/components/reference/_gitlab-sms-requirements.mdx
The token needs a higher role to set up webhooks, but this can be downgraded
> clarify why setting up GitLab SMS requires a higher role 

- src/components/reference/_triage-states.mdx
[Preview](https://deploy-preview-2036--semgrep-docs-prod.netlify.app/docs/semgrep-code/triage-remediation#removed-findings)
For https://linear.app/semgrep/issue/TEC-247/update-info-on-findings-triaged-across-refs
> update info re: findings triaged across refs

- docs/semgrep-appsec-platform/slack.md
There's an issue with deletion now where you have to unsubscribe first - it shouldn't be necessary, but if we add it to the instructions people are slightly more likely to have a smooth experience.
One note here, the page says that we should always refer to the Semgrep Slack app, but the app and the integration are technically different things. "Uninstall the Semgrep Slack app" describes the process of uninstalling it on Slack, which is not the process we're describing here, which removes the integration from Semgrep. So we may want to re-evaluate that at some point.
> Full steps currently required for removal for Slack

- docs/kb/semgrep-code/semgrepignore-ignored.md
The changes here are smaller than they look, but it was easier for me to undo the limited line length than keep it consistent. 
Mostly I did some wording cleanup, section separation, and version change.
~- [ ] If you have changed any header tag links~ all header changes are net-new
> Align style and be clearer about versions & defaults

- docs/semgrep-supply-chain/ignoring-deps.md
The behavior described in the docs has been different for a while, it's simpler now.
> Update supply chain semgrepignore docs

- docs/semgrep-appsec-platform/webhooks.md
> Add optional step to webhook setup guide for enabling broker

- docs/semgrep-appsec-platform/wiz.md
SCM support is stated in the previous section but if folks are anything like me they may skip down to Limitations when checking, so I wanted to clarify it there too.
Sidenote: couldn't we just call this section `Requirements`? A pre-requisite is a requirement also. :)
> Add SCM support to limitations too

- docs/ignoring-files-folders-code.md.template
This fixes two issues:
* `.gitignore` files are not ignored by semgrep scans (in both Semgrepignore v1 and v2)
* a `.semgrepignore` file that's not in the project tree has no effect (new in v2)
> Fix documentation relating to .semgrepignore

- docs/writing-rules/experiments/metavariable-type.md
Wonder why this is still experimental? Seems like people have adopted it.
> add supported languages for metavariable-type

- sidebars.js
This PR moves both docs on ignoring files, folders, and code/dependencies into **Core deployment**. I thought the best place for it was **Core deployment > Beyond core deployment**, so I moved the docs into this sidebar. However, it looked a bit bare, so I opted to update this section to reflect the chart that exists on the **Beyond core deployment** page. Preview:
> update Beyond core deployment sidebar

- replace-on-build.py
:heavy_check_mark: BEFORE MERGING: check that https://raw.githubusercontent.com/semgrep/semgrep/develop/src/targeting/default.semgrepignore exists
The old URL will remain available for a while but won't be updated.
This PR depends on https://github.com/semgrep/semgrep-proprietary/pull/3692 being merged and synchronized with the public semgrep repo.
> Load default Semgrepignore patterns from a new location

- src/theme/BlogListPage/index.tsx
This PR updates the img path from relative to absolute for our logo in the release notes.
---
**Before:**
_Note that this doesn't happen on the first page - must be an SPA rendering limitation._
**After**
> use absolute path so that it wont break on pg2

- docs/semgrep-ci/network-broker.md
* Make it easier for customers to see what Network Broker is used for by linking to relevant pages
* Add "code access for Semgrep Managed Scanning" as one of Network Broker's use cases
> add links to network broker use cases

- docs/semgrep-ci/network-broker.md
Currently we document Broker's outbound UDP requirement on its [repository's README](https://github.com/semgrep/semgrep-network-broker/blob/develop/README.md) but not here.
> mention outbound UDP requirement for broker

- docs/kb/semgrep-ci/jenkins-diff-scans.md
Removing whitespace before and after equals sign so snippet can be copy pasted and behave as intended.
> Jenkins diff scans kb syntax fix

- docs/deployment/managed-scanning/bitbucket.md
- docs/getting-started/quickstart-sms.md
- docs/semgrep-code/triage-remediation.md
- src/components/reference/_sms-support.mdx
SMS diff scans and triage by PR comments rely on project webhooks for BitBucket Data Center. Since project webhooks are introduced in BBDC v8.8 or above, we only support SMS diff scans and triage by PR comments for BBDC v8.8 or above. Updating docs to specify BBDC version.
> chore(sms): Specify BitBucket Data Center version supported for SMS diff scans and triage by PR comments

- docs/deployment/beyond-core-deployment.md
- sidebars.js
Was looking for the ignoring docs and would not have ocurred to me that "Beyond Core Deployment" would have it. Was looking for something like "Edit" or "Customize".
> minor category renaming from Beyond Core Deployment to Customize Core Deployment

- docs/index.md
- docs/languages/csharp.md
- docs/languages/go.md
- docs/languages/java.md
- docs/languages/javascript.md
- docs/languages/kotlin.md
- docs/languages/python.md
- docs/languages/ruby.md
- docs/languages/scala.md
- docs/languages/swift.md
- docs/supported-languages.md
- sidebars.js
- src/components/concept/_lang-callout.md
- src/components/concept/_lang-ce-intro.md
- src/components/concept/_lang-code-analyses.md
- src/components/concept/_lang-coverage.md
- src/components/concept/_lang-def-code.md
- src/components/concept/_lang-def-ssc.md
- src/components/concept/_lang-ssc-features.md
- src/components/reference/_supported-languages-table.mdx
The supported languages page is a popular TOFU doc. Having documentation for the user's specific programming language sends the signal that we are committed to providing support for that language, in addition to consolidating in one place all the information the user needs about how Semgrep supports that language.
Currently, these docs only provide information for Semgrep Code.
This update aims to provide concise feature coverage for **both SSC and Code** for existing language pages **and** add more language-specific pages (for C#, Java, see full list below).
These language-specific pages are more "formulaic" in a way as the page is meant to be a reference for every Semgrep feature available for that language (do we support lockfileless scanning for X language? do we have license …
> Beef up per-language documentation

- docs/writing-rules/autofix.md
I was going through the pricing page and realized people may not know we have 2 kinds of autofix.
> Update autofix.md to differentiate between AI and rule-based autofix

- docs/contributing/adding-a-language.md
> nit: fix comment to be a valid markdown comment

- docs/usage-and-billing.mdx
It looks like some queries are 90 days, some queries are 30 days (see [Slack thread](https://semgrepinc.slack.com/archives/C0370TA46PL/p1747329065427949?thread_ts=1747327975.632319&cid=C0370TA46PL)) - we cannot consistently say 90 days until all sources equally report it.
> revert to 30 days

- docs/kb/semgrep-appsec-platform/findings-count-differ-api-platform.md
[Preview](https://deploy-preview-2158--semgrep-docs-prod.netlify.app/docs/kb/semgrep-appsec-platform/findings-count-differ-api-platform)
> add KB article: Why do the findings count differ in the API and the Semgrep AppSec Platform UI?

- docs/languages/python.md
- docs/semgrep-supply-chain/upgrade-guidance.md
- docs/supported-languages.md
We added uv support in v1.22.0
> chore(sca): add uv to supported python package managers

- docs/supported-languages.md
- src/components/reference/_supported-languages-table.mdx
context: https://github.com/semgrep/semgrep-app/pull/21015
I expect this to be behind a FF for a very short time because the functionality is pretty simple. Imo it is fine to update the docs now. I doubt anyone will notice, and if they open a ticket we can add them to the beta
I put PHP above Rust because we'll have Reachability coverage soon
> PHP License support [SC-2445]

- docs/ignoring-files-folders-code.md.template
The information and discussion about how Semgrep handles ignorelists is spread across our comms channels and some very old tickets. I decided to place the information here in one place so that we have a unified location and place where we can refine how the various ignore features best add value to the user experience.
The central discussion involves Platform ignores vs `.semgrepignore`. The `nosem` annotation is largely straightfoward. 
> Don't forget! SAP local project ignorelist EXISTS as does implicit `.semgrepignore` BY DEFAULT when a project is scanned by `semgrep ci`.
Goal | User-defined .semgrepignore | Platform ignores | End result | Why? |
|--|--|--|--|--|
| Ignore `somefile` | Added to user-defined semgrepignore | No changes | Success | Defined in semgrepignore
| Ignore …
> Update to ignoring documentation, troubleshooting, etc.

- docs/supported-languages.md
Updates the definition of GA and beta for reachability and also updates the table to reflect that PHP is in beta
> PHP - update supported langs

- docs/ignoring-files-folders-code.md.template
Edited related code, see [pr](https://github.com/semgrep/semgrep-proprietary/pull/4030).
> fix(docs): remove documentation regarding requiring a space before nosemgrep

- docs/deployment/sso.md
Just added a detail to the warning since folks get stuck here sometimes. Dunno if this will help, but it won't hurt.
https://deploy-preview-2185--semgrep-docs-prod.netlify.app/docs/deployment/sso#turn-off-sign-in-with-github--gitlab
> Specify you want an SSO admin before disabling SCM auth

- docs/cli-reference.md.template
This is an attempt to draw attention to the fact that there are two tabs in the list of CLI commands.
[Preview](https://deploy-preview-2190--semgrep-docs-prod.netlify.app/docs/cli-reference#semgrep-ci-and-semgrep-scan-command-options)
> edit CLI reference to draw attention to the fact that there are two tabs in the list of CLI commands

- algolia-config.json
It appears the config doesn't like the use of the synonym key
> remove use of synonym in algolia config

- docs/semgrep-assistant/customize.md
> assistant: Add dialog about multiple model providers

- docs/deployment/managed-scanning/gitlab.md
- docs/semgrep-appsec-platform/bitbucket-data-center-pr-comments.md
- docs/semgrep-appsec-platform/gitlab-mr-comments.md
- docs/semgrep-ci/network-broker.md
This PR:
- updates GitLab docs to include roles and token scopes information
- updates the Network Broker doc to link out to tokens info (except for GitHub, since most use the app)
> update roles and scopes information

- docs/semgrep-supply-chain/malicious-dependencies.md
Some customers have had questions about how we generate the malicious dependency advisories, so this addition attempts to provide clarification on related points.
> Add how advisories are generated and matched to dependencies

- docs/semgrep-appsec-platform/bitbucket-data-center-pr-comments.md
In general it's preferred to send people to info about how to get support for their setup over directly including the mailto.
~- [ ] A subject matter expert (SME) reviews the content~ xs PR
> Direct to support info rather than email

- docs/contributing/semgrep-core-contributing.md
`make setup` is enough to build `semgrep-core`. `make dev-setup` installs a variety of other OCaml packages that can improve the developer experience, but they are strictly optional.
> Remove `make dev-setup` instruction

- docs/deployment/connect-scm.md
This PR updates the instructions for connecting to GitHub Cloud when not using GitHub SSO.  
- It provides more details about the options that users have for authenticating via GitHub.  
- It makes the "contact support" option more of a fallback rather than The Official Way To Do It.
Screenshot of the new text:
> Update docs for scanning github w/non-github SSO

- docs/deployment/managed-scanning/bitbucket.md
- docs/getting-started/quickstart.md
- docs/run-a-successful-pov.md
- docs/semgrep-assistant/getting-started.md
- src/components/procedure/_join-an-org.md
- src/components/procedure/_platform-signin-gitlab.md
This removes all links to the deployment checklist's permissions section if it's not relevant (currently, it is mostly relevant for GitHub users). In the future, I'll move this info to GitHub-specific pages like we do for all the other SCMs.
> remove unhelpful permissions links only

- docs/deployment/add-semgrep-other-ci.md
- docs/deployment/add-semgrep-to-ci.md
- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_semaphore-semgrep-app-sast.mdx
- src/components/code_snippets/_semaphore-semgrep-oss-sast.mdx
- src/components/reference/_ci-scheduling.mdx
This PR adds [Semaphore](https://github.com/semaphoreio/semaphore) to the CI parts of the docs. The provided docs work for the cloud and open-source+self-hosted versions Semaphore.
> docs: add Semaphore as a CI option

- docs/usage-and-billing.mdx
The goal is to align doc and the UI.
The doc says last 90 days.
The UI says last 30 days.
> fix from 90 to 30 days the usage computation

- docs/semgrep-supply-chain/dependency-search.md
Quick fix to what looks like a typo when describing why dependencies might now show up on the Dependencies page.
> Fix typo in dependency search documentation

- docs/writing-rules/data-flow/taint-mode.md
Loading: https://semgrep.dev/docs/writing-rules/data-flow/taint-mode#understanding-custom-propagators
Before:
After:
Based on https://web.dev/articles/iframe-lazy-loading
> perf(editors): Tag editor iframes as loading=lazy to avoid loading every iframe right away

- docs/semgrep-ci/sample-ci-configs.md
- src/components/code_snippets/_glcicd-semgrep-app-sast-dash.mdx
If you execute the current example, it fails with an Engine Error -14
The reason behind this is that we upload SAST findings, so we need to specify that it is a Code scan.
> This sample works only for SAST

- docs/supported-languages.md
We don't support Cocoapods, but it was in the docs as a supported package
manager
> fix(sca): remove podfile, which we don't support
